import { useMemo } from 'react';
import { createPaneConversationRenderer } from './app-conversation-pane-renderer';

type RendererOptions = Parameters<typeof createPaneConversationRenderer>[0];

export function usePaneConversationRenderer(options: RendererOptions) {
  return useMemo(
    () =>
      createPaneConversationRenderer({
        conversationHandoff: options.conversationHandoff,
        resolvedDraftPrefsFor: options.resolvedDraftPrefsFor,
        sessions: options.sessions,
        registeredProjectPath: options.registeredProjectPath,
        projectChromeLabel: options.projectChromeLabel,
        selectedSession: options.selectedSession,
        headerTitleEditingSessionId: options.headerTitleEditingSessionId,
        headerTitleDraft: options.headerTitleDraft,
        headerTitleInvalid: options.headerTitleInvalid,
        openHeaderTitleEditor: options.openHeaderTitleEditor,
        setHeaderTitleDraft: options.setHeaderTitleDraft,
        commitHeaderTitleEditor: options.commitHeaderTitleEditor,
        closeHeaderTitleEditor: options.closeHeaderTitleEditor,
        paneTranscriptRendererPending: options.paneTranscriptRendererPending,
        requestedSessionId: options.requestedSessionId,
        invokeResult: options.invokeResult,
        errors: options.errors,
        paneSubmitFor: options.paneSubmitFor,
        paneDraftSubmitFor: options.paneDraftSubmitFor,
        submit: options.submit,
        applySessionLaneResult: options.applySessionLaneResult,
        applySnapshot: options.applySnapshot,
        composerFocusRequest: options.composerFocusRequest,
        conversationNewTask: options.conversationNewTask,
        conversationClearToNewTask: options.conversationClearToNewTask,
        conversationClearProject: options.conversationClearProject,
        conversationResumeSession: options.conversationResumeSession,
        openSidebar: options.openSidebar,
        conversationOpenProjects: options.conversationOpenProjects,
        openSettings: options.openSettings,
        projects: options.projects,
        stageNewTaskModelSelection: options.stageNewTaskModelSelection,
        rememberSessionRouteForNextTask: options.rememberSessionRouteForNextTask,
        stageNewTaskWorkflow: options.stageNewTaskWorkflow,
        stageNewTaskOrchestrationMode: options.stageNewTaskOrchestrationMode,
        conversationSelectProject: options.conversationSelectProject,
        openConversationCommandSurface: options.openConversationCommandSurface,
        openFileTab: options.openFileTab,
        replaceWithInheritedSession: options.replaceWithInheritedSession,
      }),
    [
      options.conversationHandoff,
      options.resolvedDraftPrefsFor,
      options.sessions,
      options.registeredProjectPath,
      options.projectChromeLabel,
      options.selectedSession,
      options.headerTitleEditingSessionId,
      options.headerTitleDraft,
      options.headerTitleInvalid,
      options.openHeaderTitleEditor,
      options.setHeaderTitleDraft,
      options.commitHeaderTitleEditor,
      options.closeHeaderTitleEditor,
      options.paneTranscriptRendererPending,
      options.requestedSessionId,
      options.invokeResult,
      options.errors,
      options.paneSubmitFor,
      options.paneDraftSubmitFor,
      options.submit,
      options.applySessionLaneResult,
      options.applySnapshot,
      options.composerFocusRequest,
      options.conversationNewTask,
      options.conversationClearToNewTask,
      options.conversationClearProject,
      options.conversationResumeSession,
      options.openSidebar,
      options.conversationOpenProjects,
      options.openSettings,
      options.projects,
      options.stageNewTaskModelSelection,
      options.rememberSessionRouteForNextTask,
      options.stageNewTaskWorkflow,
      options.stageNewTaskOrchestrationMode,
      options.conversationSelectProject,
      options.openConversationCommandSurface,
      options.openFileTab,
      options.replaceWithInheritedSession,
    ]
  );
}
