import WebSocket from 'ws';
const targets = await (await fetch('http://127.0.0.1:9343/json')).json();
const page = targets.find((t) => t.type === 'page' && !/devtools/i.test(t.url));
const ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.once('open', res); ws.once('error', rej); });
let seq = 0; const pending = new Map();
ws.on('message', (raw) => { const m = JSON.parse(raw.toString()); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const send = (method, params = {}) => new Promise((res) => { const id = ++seq; pending.set(id, res); ws.send(JSON.stringify({ id, method, params })); });
const evalJson = async (expr) => (await send('Runtime.evaluate', { returnByValue: true, expression: expr })).result?.result?.value;
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
console.log('labels:', await evalJson(`JSON.stringify([...document.querySelectorAll('.topbar button')].map(b => b.getAttribute('aria-label')))`));
console.log(await evalJson(`(() => {
  const btns = [...document.querySelectorAll('.topbar button')];
  const b = btns.find(x => /사이드바|sidebar/i.test(x.getAttribute('aria-label')||''));
  if (!b) return 'nf';
  b.click();
  const armed = document.documentElement.classList.contains('mx-side-panel-animating');
  const cs = getComputedStyle(document.querySelector('.sidebar.session-sidebar'));
  return JSON.stringify({ armed, transition: cs.transitionProperty.slice(0, 70), dur: cs.transitionDuration.split(',')[0] });
})()`));
await wait(420);
console.log('settled:', await evalJson(`document.documentElement.classList.contains('mx-side-panel-animating')`));
await evalJson(`(() => { const b = [...document.querySelectorAll('.topbar button')].find(x => /사이드바|sidebar/i.test(x.getAttribute('aria-label')||'')); if (b) b.click(); })()`);
await wait(420);
console.log(await evalJson(`(() => {
  const b = [...document.querySelectorAll('.topbar button')].find(x => /유틸리티|utility|패널/i.test(x.getAttribute('aria-label')||'') && !/닫기 아님/.test(''));
  if (!b) return 'nf';
  b.click();
  const dock = document.querySelector('.utility-dock--persistent');
  return JSON.stringify({ label: b.getAttribute('aria-label'), anim: dock ? getComputedStyle(dock).animationName : 'no-dock' });
})()`));
await wait(500);
console.log('dock after settle:', await evalJson(`(() => { const d = document.querySelector('.utility-dock--persistent'); return d ? getComputedStyle(d).animationName : null; })()`));
ws.close();
