import WebSocket from 'ws';
const targets = await (await fetch('http://127.0.0.1:9343/json')).json();
const page = targets.find((t) => t.type === 'page' && !/devtools/i.test(t.url));
const ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.once('open', res); ws.once('error', rej); });
let seq = 0; const pending = new Map();
ws.on('message', (raw) => { const m = JSON.parse(raw.toString()); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
const send = (method, params = {}) => new Promise((res) => { const id = ++seq; pending.set(id, res); ws.send(JSON.stringify({ id, method, params })); });
const evalJson = async (expr) => (await send('Runtime.evaluate', { returnByValue: true, expression: expr })).result?.result?.value;
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
await send('Emulation.setDeviceMetricsOverride', { width: 747, height: 700, deviceScaleFactor: 0, mobile: false });
await wait(400);
await evalJson(`(() => { window.__bpAnims = []; document.addEventListener('animationstart', (e) => window.__bpAnims.push(e.animationName), true); return 'armed'; })()`);
await evalJson(`[...document.querySelectorAll('.topbar button')].find(x => (x.getAttribute('aria-label')||'') === '패널 열기').click()`);
await wait(50);
console.log('t50:', await evalJson(`(() => { const p = document.querySelector('.bottom-panel'); if (!p) return 'no-panel'; const cs = getComputedStyle(p); return JSON.stringify({ settled: p.dataset.settled || null, anim: cs.animationName, dur: cs.animationDuration, reduced: matchMedia('(prefers-reduced-motion: reduce)').matches }); })()`));
await wait(600);
console.log('starts:', await evalJson(`JSON.stringify(window.__bpAnims)`));
await evalJson(`[...document.querySelectorAll('.topbar button')].find(x => (x.getAttribute('aria-label')||'') === '패널 닫기').click()`);
await send('Emulation.clearDeviceMetricsOverride');
ws.close();
