// Office capability catalog: the actions, per-format paths/operations/
// properties, and the backend sets the runtime advertises.

export const OFFICE_ACTIONS = Object.freeze([
  'detect',
  'transactions',
  'recover',
  'describe',
  'author',
  'create',
  'attach',
  'open',
  'secure',
  'begin',
  'snapshot',
  'get',
  'query',
  'batch',
  'diff',
  'commit',
  'rollback',
  'issues',
  'qa',
  'validate',
  'render',
  'save',
  'finalize',
  'close',
]);

export const COMMON = {
  actions: OFFICE_ACTIONS,
  observation: {
    selection:
      'attached and visible Microsoft Office snapshots include the active range, paragraph, slide, or shapes; background and portable sessions report document state only',
  },
  batch: {
    atomic:
      'all modes roll back failed batches; live Word/PowerPoint use Office Undo boundaries and live Excel restores an in-memory checkpoint without saving',
    operationShape:
      '{ op, target-specific fields, properties?, allowNoChange? }; silent no-op results roll back unless requireChanges:false',
    initialOperations:
      'create/open accept known operations; their results prove the edit without a redundant snapshot unless snapshotAfter:true',
  },
};

const TABULAR = {
  paths: ['/sheet[NAME]', '/sheet[NAME]/cell[A1]', '/sheet[NAME]/range[A1:C10]'],
  operations: {
    common: [
      'replace_text',
      'set_cell',
      'set_formula',
      'set_range',
      'append_row',
      'clear_cell',
      'insert_rows',
      'delete_rows',
      'insert_columns',
      'delete_columns',
    ],
    office: [],
    portable: [],
  },
  properties: {
    cell: ['value', 'formula'],
    structure: ['row', 'column', 'count', 'range'],
    safety: ['formulaLikeValue', 'raggedRow', 'utf8'],
  },
};

export const CATALOG = {
  docx: {
    paths: [
      '/body/p[N]',
      '/body/p[N]/run[N]',
      '/body/tbl[N]/row[N]/cell[N]',
      '/body/comment[N]',
      '/body/comment-thread[N]',
      '/body/revision[N]',
      '/body/footnote[N]',
      '/body/endnote[N]',
      '/body/content-control[N]',
    ],
    operations: {
      common: [
        'replace_text',
        'fill_template',
        'compose_document',
        'append_text',
        'set_paragraph_text',
        'set_table_cell',
        'remove_paragraph',
        'move_paragraph',
        'add_table',
        'set_table_style',
        'merge_table_cells',
        'set_table_cell_style',
        'set_paragraph_format',
        'set_font',
        'add_image',
        'set_header_footer',
        'set_page',
        'add_page_numbers',
        'insert_break',
        'set_list',
        'add_hyperlink',
        'insert_table_row',
        'delete_table_row',
        'insert_table_column',
        'delete_table_column',
        'insert_toc',
        'add_bookmark',
        'add_note',
        'set_content_control',
        'add_comment',
        'delete_comment',
        'add_provenance',
        'fit_table',
        'resolve_revision',
        'resolve_revisions',
        'track_changes',
        'add_comment_reply',
        'set_comment_resolved',
        'normalize_runs',
      ],
      office: ['set_paragraph_style'],
      // set_run_text addresses OOXML runs. Word exposes no run object, so the
      // Office backend could only edit the Nth word instead, silently rewriting
      // different text for the same index. It stays portable-only rather than
      // meaning two different things. normalize_runs is common so one opening
      // batch works on both backends: Word searches across runs itself and
      // reports the operation as unnecessary (changed:false).
      portable: ['set_paragraph_style', 'set_run_text'],
    },
    properties: {
      paragraph: ['style'],
      font: ['name', 'nameEastAsia', 'size', 'bold', 'italic', 'underline', 'color', 'hidden'],
      page: ['orientation', 'topMargin', 'bottomMargin', 'leftMargin', 'rightMargin', 'columns', 'columnSpacing'],
      headerFooter: ['section', 'kind', 'header', 'text'],
      table: [
        'style',
        'textStyle',
        'fontName',
        'fontNameEastAsia',
        'fontSize',
        'color',
        'spacingAfter',
        'columnWidths',
        'rowHeights',
        'borders',
        'shading',
        'alignment',
        'columnAlignments',
        'repeatHeader',
        'headerBold',
      ],
      tableCell: [
        'fillColor',
        'horizontalAlignment',
        'verticalAlignment',
        'width',
        'fontName',
        'fontNameEastAsia',
        'fontSize',
        'bold',
        'italic',
        'color',
      ],
      paragraphFormat: [
        'alignment',
        'spacingBefore',
        'spacingAfter',
        'lineSpacing',
        'keepWithNext',
        'keepTogether',
        'widowControl',
        'pageBreakBefore',
        'border',
        'shading',
        'indentLeft',
        'indentRight',
        'indentFirstLine',
        'tabStops',
        'listKind',
        'listLevel',
      ],
      comment: ['author', 'initials', 'date', 'text', 'anchoredText', 'resolved', 'replies'],
      contentControl: ['tag', 'title', 'lock', 'text'],
      revision: ['author', 'date', 'type', 'typeCode', 'text', 'resolution'],
      fields: ['toc', 'page', 'numPages', 'pageBreak', 'sectionBreak'],
      links: ['address', 'subAddress', 'display', 'bookmark'],
      provenance: ['source.document', 'source.target', 'source.label'],
      design: [
        'profile',
        'purpose',
        'expressionMode',
        'intent',
        'audience',
        'tone',
        'density',
        'palette',
        'typography',
        'signature',
        'content.packageId',
        'content.audience',
        'content.objective',
        'content.decision',
        'content.period',
        'content.facts',
        'content.claims',
        'review',
      ],
    },
  },
  xlsx: {
    paths: ['/sheet[NAME]', '/sheet[NAME]/cell[A1]', '/sheet[NAME]/range[A1:C10]'],
    operations: {
      common: [
        'replace_text',
        'set_cell',
        'set_formula',
        'set_range',
        'append_row',
        'clear_cell',
        'compose_sheet',
        'add_sheet',
        'delete_sheet',
        'rename_sheet',
        'set_style',
        'merge_cells',
        'unmerge_cells',
        'freeze_panes',
        'autofit_range',
        'set_page_setup',
        'set_sheet_view',
        'add_chart',
        'set_drawing',
        'delete_drawing',
        'add_table',
        'insert_rows',
        'delete_rows',
        'insert_columns',
        'delete_columns',
        'set_autofilter',
        'sort_range',
        'set_sheet_visibility',
        'set_row_visibility',
        'set_column_visibility',
        'set_header_footer',
        'define_name',
        'delete_name',
        'copy_sheet',
        'add_image',
        'set_hyperlink',
        'protect_sheet',
        'unprotect_sheet',
        'add_validation',
        'add_conditional_format',
        'delete_conditional_formats',
        'add_note',
        'delete_note',
        'add_provenance',
        'add_pivot_table',
      ],
      office: [],
      portable: [],
    },
    properties: {
      cellStyle: [
        'fontName',
        'fontSize',
        'bold',
        'italic',
        'color',
        'fillColor',
        'numberFormat',
        'horizontalAlignment',
        'verticalAlignment',
        'wrapText',
        'locked',
        'borders',
      ],
      chart: [
        'chartType',
        'left',
        'top',
        'width',
        'height',
        'title',
        'seriesColors',
        'showValues',
        'showLegend',
        'zeroBaseline',
        'valueNumberFormat',
        'dataLabelPosition',
        'dataLabelColor',
      ],
      table: ['name', 'style'],
      pivot: ['source', 'destination', 'name', 'rows', 'columns', 'values'],
      note: ['text', 'author'],
      structure: ['row', 'column', 'count', 'range', 'referenceAware'],
      links: ['address', 'text'],
      protection: ['password', 'allowFormattingCells', 'allowSorting', 'allowFiltering'],
      audit: ['conditionalFormats', 'formulaLineage', 'checksSheet', 'hardcodeSource', 'rogueHardcode'],
      pageSetup: [
        'printArea',
        'fitToContent',
        'orientation',
        'fitToPagesWide',
        'fitToPagesTall',
        'centerHorizontally',
        'centerVertically',
        'topMargin',
        'bottomMargin',
        'leftMargin',
        'rightMargin',
      ],
      sheetView: ['showGridlines', 'zoom'],
      provenance: ['source.document', 'source.target', 'source.label'],
      design: [
        'profile',
        'purpose',
        'expressionMode',
        'intent',
        'audience',
        'tone',
        'density',
        'palette',
        'typography',
        'signature',
        'content.packageId',
        'content.audience',
        'content.objective',
        'content.decision',
        'content.period',
        'content.facts',
        'content.claims',
        'review',
      ],
    },
  },
  pptx: {
    paths: ['/slide[N]', '/slide[N]/shape[N]'],
    stableTargets:
      'Portable batch operations may replace slide/shape indices with slideId/shapeId from snapshot. IDs survive ordering changes; conflicting indices fail rather than edit a different element. COM continues to use indices.',
    operations: {
      common: [
        'replace_text',
        'fill_template',
        'set_text',
        'add_textbox',
        'delete_shape',
        'add_slide',
        'delete_slide',
        'move_slide',
        'set_notes',
        'add_image',
        'add_shape',
        'add_table',
        'set_shape',
        'set_slide_background',
        'import_slides',
        'use_template_page',
        'replace_image',
        'set_table_data',
        'fit_text',
        'add_chart',
        'set_chart_data',
        'duplicate_slide',
        'z_order',
        'align_shapes',
        'distribute_shapes',
        'keep_slides',
        'set_hyperlink',
        'add_provenance',
        'set_layout',
        'crop_image',
        'set_transition',
        'set_footer',
        'set_slide_number',
        'set_slide_visibility',
        'set_chart_axis',
        'set_chart_data_labels',
        'group_shapes',
        'ungroup_shape',
        'set_chart_trendline',
        'set_chart_error_bars',
        'set_chart_series',
        'add_comment',
        'delete_comment',
        'apply_theme',
        'add_media',
        'add_animation',
      ],
      office: [],
      portable: [],
    },
    properties: {
      shape: [
        'left',
        'top',
        'width',
        'height',
        'rotation',
        'fillColor',
        'fillTransparency',
        'lineColor',
        'lineTransparency',
        'lineWidth',
        'shadow',
        'marginLeft',
        'marginTop',
        'marginRight',
        'marginBottom',
        'fontName',
        'fontSize',
        'bold',
        'italic',
        'color',
        'alignment',
        'verticalAlignment',
        'paragraphSpacing',
        'altText',
      ],
      chart: [
        'chartType',
        'left',
        'top',
        'width',
        'height',
        'title',
        'series',
        'axis',
        'dataLabels',
        'seriesType',
        'secondaryAxis',
        'trendline',
        'errorBars',
        'showValues',
        'showLegend',
        'zeroBaseline',
        'valueNumberFormat',
        'dataLabelPosition',
        'dataLabelColor',
      ],
      slide: ['background', 'layout', 'layoutName'],
      placeholder: ['type', 'index'],
      table: [
        'rows',
        'columns',
        'values',
        'fontName',
        'fontSize',
        'color',
        'headerFillColor',
        'headerColor',
        'bodyFillColor',
        'headerRowHeight',
        'bodyRowHeight',
      ],
      template: ['tokens', 'strict'],
      authoring: [
        'shapeType',
        'paragraphs',
        'bullet',
        'level',
        'hyperlink',
        'zOrder',
        'align',
        'distribute',
        'group',
        'crop',
        'theme',
        'footer',
        'slideNumber',
      ],
      transition: ['effect', 'duration', 'advanceOnTime', 'advanceTime'],
      animation: ['effect', 'trigger', 'duration', 'delay'],
      media: ['kind', 'link', 'embed', 'poster'],
      comment: ['author', 'initials', 'left', 'top'],
      provenance: ['source.document', 'source.target', 'source.label'],
      design: [
        'profile',
        'purpose',
        'expressionMode',
        'intent',
        'audience',
        'tone',
        'density',
        'palette',
        'typography',
        'signature',
        'content.packageId',
        'content.audience',
        'content.objective',
        'content.decision',
        'content.period',
        'content.facts',
        'content.claims',
        'template',
        'deck.backgroundMode',
        'deck.dominantColorRole',
        'deck.motif',
        'deck.spacingScale',
        'deck.sectionSlides',
        'deck.roles',
        'deck.requireSlidePlan',
        'deck.templateMode',
        'review',
        'reviewed',
        'reviewToken',
        'critique',
      ],
    },
  },
  pdf: {
    paths: ['/page[N]', '/field[N]', '/outline[N]', '/attachments[N]', '/metadata'],
    operations: {
      common: [
        'add_text',
        'watermark',
        'highlight',
        'add_link',
        'stamp_image',
        'ocr_pages',
        'rotate_pages',
        'delete_pages',
        'move_page',
        'extract_pages',
        'split_pages',
        'fill_form',
        'add_form_field',
        'flatten_form',
        'preview_fields',
        'merge_pdf',
        'add_bookmark',
        'add_attachment',
        'extract_attachment',
        'compress',
        'set_metadata',
      ],
      office: [],
      portable: [],
    },
    properties: {
      text: ['x', 'y', 'size', 'color', 'opacity', 'rotation', 'align'],
      metadata: ['title', 'author', 'subject', 'keywords', 'creator'],
      form: [
        'name',
        'type',
        'page',
        'x',
        'y',
        'width',
        'height',
        'options',
        'value',
        'multiline',
        'multiselect',
        'editable',
        'maxLength',
        'fontSize',
        'required',
        'readOnly',
        'fontPath',
      ],
      attachment: ['path', 'name', 'mimeType', 'description', 'index', 'output'],
      textFont: ['fontPath'],
      create: [
        'blocks',
        'fields',
        'properties.pageSize',
        'properties.orientation',
        'properties.margin',
        'properties.fontPath',
        'properties.pageNumbers',
        'properties.footer',
        'properties.title',
        'properties.author',
        'properties.subject',
        'properties.keywords',
      ],
      units: ['points; origin bottom-left; 1 inch = 72 pt; A4 = 595.28 x 841.89'],
      unsupportedSecurity: ['secureRedaction', 'digitalSignature', 'PDF/A'],
    },
  },
  csv: TABULAR,
  tsv: TABULAR,
};

export const BACKENDS = new Set(['microsoft-office-com', 'mixdog-ooxml', 'mixdog-tabular', 'mixdog-pdf']);
export const VIRTUAL_OPERATIONS = new Set(['compose_document', 'compose_sheet', 'use_template_page']);
