import {
  TOOL_SYNC_EXECUTION_CONTRACT,
} from '../shared/tool-execution-contract.mjs';
import { OFFICE_ACTIONS } from './capabilities.mjs';

export const TOOL_DEFS = [
  {
    name: 'office',
    title: 'Mixdog Office Use',
    description: 'Create, inspect, edit, review, secure, and save DOCX/DOTX, XLSX/XLTX/XLSM, PPTX/POTX, CSV/TSV, and PDF files. For creation or known targets, put all known operations on create/open, use one batch for later edits, then finalize once. Inspect unfamiliar existing documents before editing. Successful operation results prove edits; do not snapshot again unless content or layout itself needs inspection. Call describe only when exact fields or backend support are unknown. Keep finalize review enabled for deliverables. Batches are atomic and reject no-ops by default; checkpoint transactions detect external conflicts. attach targets an exact registered Office document, visible reuses or opens one visible document, background edits a protected output copy, and portable reports unsupported work. Background template edits preserve the source; portable preserves macro containers but never runs VBA. '
      + TOOL_SYNC_EXECUTION_CONTRACT,
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: OFFICE_ACTIONS,
          description: 'Choose one action. detect/describe discover availability and capabilities; transactions/recover and begin/diff/commit/rollback manage checkpoints; create/attach/open start sessions; snapshot/get/query inspect; batch edits; issues/qa/render/validate review; save/finalize/close finish. secure writes an encrypted or decrypted PDF output. finalize combines review, save, validation, and close.',
        },
        path: { type: 'string', description: 'Document path; relative paths resolve from the caller project.' },
        format: { type: 'string', enum: ['docx', 'dotx', 'docm', 'dotm', 'xlsx', 'xltx', 'xlsm', 'xltm', 'pptx', 'potx', 'pptm', 'potm', 'csv', 'tsv', 'pdf'], description: 'Format for describe/create without a path or session.' },
        backend: { type: 'string', enum: ['microsoft-office-com', 'mixdog-ooxml', 'mixdog-tabular', 'mixdog-pdf'], description: 'describe only: filter support by backend.' },
        operation: { type: 'string', description: 'describe only: return one compact operation input contract.' },
        session: { type: 'string', description: 'Session id from create/open/attach; a path may open one implicitly.' },
        transaction: { type: 'string', description: 'Transaction id for recover.' },
        strategy: { type: 'string', enum: ['commit', 'rollback', 'discard'], description: 'Recovery result for a journaled transaction.' },
        security: { type: 'string', enum: ['encrypt', 'decrypt'], description: 'PDF secure operation; requires qpdf and output.' },
        password: { type: 'string', description: 'PDF user/decryption password; omitted from summaries.' },
        ownerPassword: { type: 'string', description: 'PDF encryption owner password; defaults to password.' },
        mode: {
          type: 'string',
          enum: ['auto', 'attach', 'visible', 'background', 'portable', 'live'],
          description: 'auto attaches to an exact registered document or chooses background/portable. attach never opens a duplicate; visible reuses or opens visibly; background edits an owned output copy; portable uses Mixdog backends. live aliases attach.',
        },
        output: { type: 'string', description: 'Background/portable output copy or render destination; defaults beside source.' },
        target: { type: 'string', description: 'Stable path from snapshot/query, e.g. /body/p[2] or /sheet[Data]/cell[A1].' },
        query: { type: 'string', description: 'Case-insensitive structured-value search.' },
        properties: { type: 'object', additionalProperties: true, description: 'PDF create settings such as fontPath.' },
        blocks: { type: 'array', items: { type: 'object', additionalProperties: true }, description: 'PDF create blocks: heading, paragraph, table, image, or pagebreak.' },
        fields: { type: 'array', items: { type: 'object', additionalProperties: true }, description: 'PDF form fields; layout is linted before writing.' },
        operations: {
          type: 'array',
          description: 'Atomic edits for batch or create/open; later items may target earlier results. Call describe only when an op\'s exact fields or backend support are unknown. append_text creates a real DOCX paragraph; fill_template accepts tokens/strict; XLSX autofit_range accepts cells or columns such as A:D. Existing-PDF non-Latin text/watermarks require properties.fontPath.',
          items: {
            type: 'object',
            additionalProperties: true,
            properties: {
              op: { type: 'string' },
              find: { type: 'string' },
              replace: { type: 'string' },
              text: { type: 'string' },
              value: {},
              values: { type: 'array' },
              tokens: { type: 'object', additionalProperties: true },
              source: { type: 'object', additionalProperties: true },
              strict: { type: 'boolean' },
              style: { type: 'string' },
              allowNoChange: { type: 'boolean' },
              sheet: { type: 'string' },
              cell: { type: 'string' },
              range: { type: 'string' },
              slide: { type: 'integer', minimum: 1 },
              shape: { type: 'integer', minimum: 1 },
              page: { type: 'integer', minimum: 1 },
              pages: { type: 'array', items: { type: 'integer', minimum: 1 } },
              properties: { type: 'object', additionalProperties: true },
            },
            required: ['op'],
          },
        },
        save: { type: 'boolean', description: 'Save a live document after batch/close.' },
        snapshotAfter: { type: 'boolean', description: 'create/open: include a full post-edit snapshot; defaults false because operation results already prove edits.' },
        requireChanges: { type: 'boolean', description: 'Reject and roll back changed:false operations; defaults true.' },
        review: { type: 'boolean', description: 'finalize: run QA and render; defaults true. Keep enabled for deliverables.' },
        failOn: { type: 'string', enum: ['error', 'warning'], description: 'finalize: keep open at this severity; defaults warning for created deliverables and error for opened documents.' },
        overwrite: { type: 'boolean', description: 'create: replace an existing target.' },
        maxChars: { type: 'integer', minimum: 1000, maximum: 100000, description: 'Snapshot text cap; default 30000.' },
        cursor: { type: 'string', description: 'Snapshot continuation cursor; edits make it stale.' },
        limit: { type: 'integer', minimum: 1, maximum: 10000, description: 'Snapshot scan size; large live Excel ranges return rowBlocks.' },
        sheet: { type: 'string', description: 'Spreadsheet sheet selector; XLSX defaults to active/first.' },
        range: { type: 'string', description: 'Spreadsheet range selector, e.g. A1:H5000.' },
        includeStyles: { type: 'boolean', description: 'Include cell styles when the selected page is small enough.' },
        includeSelection: { type: 'boolean', description: 'Include active selection; defaults true for attach/visible.' },
        pages: { type: 'array', items: { type: 'integer', minimum: 1 }, description: 'Page/slide numbers; render defaults to all pages, compressed into at most 12 contact sheets when needed, and reports visualCoverage.' },
        maxWidth: { type: 'integer', minimum: 256, maximum: 2400, description: 'Rendered image width; default 1400.' },
        autoFix: { type: 'boolean', description: 'qa: apply deterministic fit/autofit repairs.' },
        auditProfile: { type: 'string', enum: ['financial-model', 'model-backed-deck'], description: 'Optional stricter QA profile.' },
        compatibility: { type: 'boolean', description: 'validate: also reopen with LibreOffice when available.' },
      },
      required: ['action'],
      additionalProperties: false,
    },
    annotations: {
      title: 'Mixdog Office Use',
      readOnlyHint: false,
      destructiveHint: true,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
];
