import {
  TOOL_SYNC_EXECUTION_CONTRACT,
} from '../shared/tool-execution-contract.mjs';
import { OFFICE_ACTIONS } from './capabilities.mjs';

export const TOOL_DEFS = [
  {
    name: 'office',
    title: 'Mixdog Office Use',
    description: 'Office files. Direct: {action:"create",path,format,mode,operations:[{op,...}],finalize:true,overwrite?}. Common ops: DOCX append_text; XLSX/CSV/TSV set_range; PPTX add_slide/add_textbox; PDF add_text. secure handles PDF security. For inspected sessions use action:"batch" with session, all remaining operations, and finalize:true. Put all known operations in one ordered array across pages/slides/sheets/types; split only for result-dependent input or a backend-required pass. Inspect unfamiliar existing files first. Operation results prove edits; no snapshot unless content or layout needs inspection. Describe only unknown fields/support. Keep review for deliverables. Visual deliverables follow brief→structure→design→render→critique: prefer a user or existing template, otherwise choose editorial/technical/data and set subject-specific palette, type, layout, and signature. Use compose_document/compose_sheet/compose_slide instead of freehand styling. For PPTX vary semantic layouts and meaningful visuals; avoid generic blue, decorative stripes/rules, and repeated card grids. Render every slide, polish, then finalize with the reviewToken and one scored critique per slide. Batches are atomic and reject no-ops; transactions detect external conflicts. attach targets an exact registered document; visible reuses or opens visibly; background edits a protected copy; portable reports unsupported work. Templates preserve the source; portable preserves macros but never runs VBA. '
      + TOOL_SYNC_EXECUTION_CONTRACT,
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: OFFICE_ACTIONS,
          description: 'detect/describe discover; transactions/recover and begin/diff/commit/rollback checkpoint; create/attach/open start; snapshot/get/query inspect; batch edits; issues/qa/render/validate review; save/finalize/close finish; secure writes PDF. Prefer finalize:true on create/open/batch.',
        },
        path: { type: 'string', description: 'Document path; relative paths resolve from the caller project.' },
        format: { type: 'string', enum: ['docx', 'dotx', 'docm', 'dotm', 'xlsx', 'xltx', 'xlsm', 'xltm', 'pptx', 'potx', 'pptm', 'potm', 'csv', 'tsv', 'pdf'], description: 'Format for describe/create without a path or session.' },
        backend: { type: 'string', enum: ['microsoft-office-com', 'mixdog-ooxml', 'mixdog-tabular', 'mixdog-pdf'], description: 'describe only: filter support by backend.' },
        operation: { type: 'string', description: 'describe only: return one compact operation input contract.' },
        session: { type: 'string', description: 'Session id from create/open/attach; a path may open one implicitly.' },
        transaction: { type: 'string', description: 'Transaction id for recover.' },
        strategy: { type: 'string', enum: ['commit', 'rollback', 'discard'], description: 'Recovery result for a journaled transaction.' },
        security: { type: 'string', enum: ['encrypt', 'decrypt'], description: 'PDF secure operation; requires qpdf and output.' },
        password: { type: 'string', description: 'PDF user/decryption password; omitted from summaries.' },
        ownerPassword: { type: 'string', description: 'PDF encryption owner password; defaults to password.' },
        mode: {
          type: 'string',
          enum: ['auto', 'attach', 'visible', 'background', 'portable', 'live'],
          description: 'auto attaches to an exact registered document or chooses background/portable. attach never opens a duplicate; visible reuses or opens visibly; background edits an owned output copy; portable uses Mixdog backends. live aliases attach.',
        },
        output: { type: 'string', description: 'Background/portable output copy or render destination; defaults beside source.' },
        target: { type: 'string', description: 'Stable path from snapshot/query, e.g. /body/p[2] or /sheet[Data]/cell[A1].' },
        query: { type: 'string', description: 'Case-insensitive structured-value search.' },
        queryKind: { type: 'string', enum: ['text', 'pdf-layout', 'pdf-tables', 'pdf-images'], description: 'Specialized PDF inspection; text is the default.' },
        properties: { type: 'object', additionalProperties: true, description: 'PDF create settings such as fontPath.' },
        design: { type: 'object' },
        blocks: { type: 'array', items: { type: 'object', additionalProperties: true }, description: 'PDF create blocks: heading, paragraph, table, image, or pagebreak.' },
        fields: { type: 'array', items: { type: 'object', additionalProperties: true }, description: 'PDF form fields; layout is linted before writing.' },
        operations: {
          type: 'array',
          description: 'Atomic edits. Put every operation whose inputs are known in one batch; split only for result-dependent input. Semantic create ops: compose_document, compose_sheet, compose_slide. Call describe only when fields/support are unknown. fill_template accepts tokens/strict; autofit_range accepts A:D; non-Latin PDF text needs properties.fontPath.',
          items: {
            type: 'object',
            additionalProperties: true,
            properties: {
              op: { type: 'string' },
              find: { type: 'string' },
              replace: { type: 'string' },
              text: { type: 'string' },
              value: {},
              values: { type: 'array' },
              tokens: { type: 'object', additionalProperties: true },
              source: { type: 'object', additionalProperties: true },
              strict: { type: 'boolean' },
              style: { type: 'string' },
              allowNoChange: { type: 'boolean' },
              sheet: { type: 'string' },
              cell: { type: 'string' },
              range: { type: 'string' },
              slide: { type: 'integer', minimum: 1 },
              shape: { type: 'integer', minimum: 1 },
              page: { type: 'integer', minimum: 1 },
              pages: { type: 'array', items: { type: 'integer', minimum: 1 } },
              properties: { type: 'object', additionalProperties: true },
            },
            required: ['op'],
          },
        },
        assertions: {
          type: 'array',
          items: { type: 'object', additionalProperties: true },
          description: 'XLSX validate/finalize checks: cell-value, cell-formula, tie-out, no-errors, or formula-consistency.',
        },
        save: { type: 'boolean', description: 'Save a live document after batch/close.' },
        finalize: { type: 'boolean', description: 'Review, save, validate, close. Scratch PPTX stays open until a rendered design review is acknowledged.' },
        snapshotAfter: { type: 'boolean', description: 'create/open full post-edit snapshot; defaults false because operation results prove edits.' },
        requireChanges: { type: 'boolean', description: 'Reject and roll back changed:false operations; defaults true.' },
        review: { type: 'boolean', description: 'finalize: run structural, visual, and design QA plus render; defaults true. Keep enabled for deliverables.' },
        failOn: { type: 'string', enum: ['error', 'warning'], description: 'finalize: keep open at this severity; defaults warning for created deliverables and error for opened documents.' },
        overwrite: { type: 'boolean', description: 'create: replace an existing target.' },
        maxChars: { type: 'integer', minimum: 1000, maximum: 100000, description: 'Snapshot text cap; default 30000.' },
        cursor: { type: 'string', description: 'Snapshot continuation cursor; edits make it stale.' },
        limit: { type: 'integer', minimum: 1, maximum: 10000, description: 'Snapshot scan size; large live Excel ranges return rowBlocks.' },
        sheet: { type: 'string', description: 'Spreadsheet sheet selector; XLSX defaults to active/first.' },
        range: { type: 'string', description: 'Spreadsheet range selector, e.g. A1:H5000.' },
        includeStyles: { type: 'boolean', description: 'Include cell styles when the selected page is small enough.' },
        includeSelection: { type: 'boolean', description: 'Include active selection; defaults true for attach/visible.' },
        pages: { type: 'array', items: { type: 'integer', minimum: 1 }, description: 'Page/slide numbers; render defaults to all pages, compressed into at most 12 contact sheets when needed, and reports visualCoverage.' },
        maxWidth: { type: 'integer', minimum: 256, maximum: 2400, description: 'Rendered image width; default 1400.' },
        autoFix: { type: 'boolean', description: 'qa: apply deterministic fit/autofit repairs.' },
        auditProfile: { type: 'string', enum: ['financial-model', 'model-backed-deck', 'redlining'], description: 'Optional stricter QA profile.' },
        author: { type: 'string', description: 'Redlining audit author or provenance label.' },
        downloadDependencies: { type: 'boolean', description: 'Allow first-use validator or OCR language download; defaults true.' },
        compatibility: { type: 'boolean', description: 'validate: also reopen with LibreOffice when available.' },
      },
      required: ['action'],
      additionalProperties: false,
    },
    annotations: {
      title: 'Mixdog Office Use',
      readOnlyHint: false,
      destructiveHint: true,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
];
