export const BROWSER_ACTIONS: readonly string[];
export const BROWSER_DEVTOOLS_ACTIONS: readonly string[];
export const BROWSER_PAGE_ACTIONS: readonly string[];
export const BROWSER_TOOL_NAME: 'browser';
export const BROWSER_DEVTOOLS_TOOL_NAME: 'browser_devtools';
export const BROWSER_TOOL_NAMES: readonly string[];
export function browserToolForAction(action: string): string;
export const BROWSER_OBSERVATION_ACTIONS: readonly string[];
export const BROWSER_POSTCONDITION_ACTIONS: readonly string[];
export const BROWSER_SEQUENCE_STEP_ACTIONS: readonly string[];
