// Session capability names the renderer may invoke and their request/result shapes.
import type { SessionSnapshot } from './contract-session';

// Public session features that are safe to expose to the renderer. Keeping this
// list explicit prevents the desktop bridge from becoming arbitrary method
// execution while still making the TUI's existing session capabilities
// available to the GUI.
export const DESKTOP_CAPABILITIES = [
  'prioritizeQueued',
  'restoreQueued',
  'rewindToItem',
  'setEffort',
  'setToolMode',
  'getAutoClear',
  'setAutoClear',
  'getUpdateSettings',
  'setAutoUpdate',
  'checkForUpdate',
  'runUpdateNow',
  'getUpdateStatus',
  'getProfile',
  'setProfile',
  'getCompactionSettings',
  'setCompactionSettings',
  'getRecapSettings',
  'setRecapEnabled',
  'getToolModuleSettings',
  'setWebSearchEnabled',
  'setMemoryToolsEnabled',
  'getDeveloperSettings',
  'setDeveloperOption',
  'setBuiltinToolEnabled',
  'installBuiltinFeature',
  'getTidyEngineStatus',
  'getTidyInstallStatus',
  'installLocalProviderModel',
  'startLocalProviderInstallation',
  'cancelLocalProviderInstallation',
  'setLocalProviderIdleTtl',
  'setLocalProviderContext',
  'getLocalProviderModelDetails',
  'startLocalProviderModelMaintenance',
  'deleteLocalProviderModel',
  'getVoiceStatus',
  'toggleVoice',
  'claimSetupRequest',
  'isSetupRequestActive',
  'completeSetupRequest',
  'agentControl',
  'taskControl',
  'goalControl',
  'toolsStatus',
  'selectTools',
  'getSystemShell',
  'setSystemShell',
  'mcpStatus',
  'getMcpServerConfig',
  'reconnectMcp',
  'addMcpServer',
  'saveMcpServer',
  'removeMcpServer',
  'setMcpServerEnabled',
  'getDisabledSkills',
  'setDisabledSkills',
  'setExtensionScope',
  'skillsStatus',
  'skillContent',
  'addSkill',
  'saveSkill',
  'reloadSkills',
  'pluginsStatus',
  'reloadPlugins',
  'addPlugin',
  'updatePlugin',
  'setPluginEnabled',
  'removePlugin',
  'enablePluginMcp',
  'contextStatus',
  'inheritancePreflight',
  'getSessionReviewDiff',
  'getTurnReviewDiff',
  'revertTurnReview',
  'revertTurnReviewFile',
  'memoryControl',
  'recall',
  'runDoctor',
  'compact',
  'listPresets',
  'setModel',
  'getWebSearchRoute',
  'listWebSearchModels',
  'setWebSearchRoute',
  'listAgents',
  'listWorkflows',
  'getOutputStyle',
  'listOutputStyles',
  'setOutputStyle',
  'setWorkflow',
  'getOrchestrationMode',
  'setOrchestrationMode',
  'listThemes',
  'getTheme',
  'setTheme',
  'transcribeAudio',
  'resizeImage',
  'setAgentRoute',
  'getWorkflowPack',
  'saveWorkflowPack',
  'createWorkflow',
  'deleteWorkflow',
  'getAgentDefinition',
  'saveAgentDefinition',
  'deleteAgentDefinition',
  'listProviders',
  'listProviderModels',
  'getProviderSetup',
  'getProviderAccounts',
  'updateProviderAccounts',
  'getUsageDashboard',
  'getUsageStats',
  'consumeCodexRateLimitResetCredit',
  'getOnboardingStatus',
  'getOAuthProviderLoginStatus',
  'skipOnboarding',
  'completeOnboarding',
  'loginOAuthProvider',
  'beginOAuthProviderLogin',
  'completeOAuthProviderLogin',
  'cancelOAuthProviderLogin',
  'saveProviderApiKey',
  'saveOpenCodeGoUsageAuth',
  'saveOpenAIUsageSessionKey',
  'authenticateProvider',
  'forgetProviderAuth',
  'getChannelSetup',
  'setWebhookConfig',
  'saveSchedule',
  'deleteSchedule',
  'setScheduleEnabled',
  'runScheduleNow',
  'saveWebhook',
  'deleteWebhook',
  'setWebhookEnabled',
  // Media studio (image/video generation).
  'listMediaLanes',
  'listMediaAssets',
  'readMediaAsset',
  'cacheMediaThumbnail',
  'resolveMediaFile',
  'getMediaJob',
  'getMediaDefault',
  'setMediaDefault',
  'startMediaJob',
  'cancelMediaJob',
  'deleteMediaAsset',
  'openMediaAsset',
  'openMediaFolder',
  'clear',
] as const;

export type DesktopCapability = (typeof DESKTOP_CAPABILITIES)[number];

export const DESKTOP_READ_CAPABILITIES = [
  'isSetupRequestActive',
  'getLocalProviderModelDetails',
  'getAutoClear',
  'getUpdateSettings',
  'getUpdateStatus',
  'getProfile',
  'getCompactionSettings',
  'getRecapSettings',
  'getToolModuleSettings',
  'getDeveloperSettings',
  'getTidyEngineStatus',
  'getTidyInstallStatus',
  'getVoiceStatus',
  'toolsStatus',
  'getSystemShell',
  'mcpStatus',
  'getMcpServerConfig',
  'getDisabledSkills',
  'skillsStatus',
  'skillContent',
  'pluginsStatus',
  'contextStatus',
  'inheritancePreflight',
  'getSessionReviewDiff',
  'getTurnReviewDiff',
  'listPresets',
  'getWebSearchRoute',
  'listWebSearchModels',
  'listAgents',
  'listWorkflows',
  'getWorkflowPack',
  'getOrchestrationMode',
  'getAgentDefinition',
  'getOutputStyle',
  'listOutputStyles',
  'listThemes',
  'getTheme',
  'listProviders',
  'listProviderModels',
  'getProviderSetup',
  'getUsageDashboard',
  'getUsageStats',
  'getProviderAccounts',
  'getOnboardingStatus',
  'getOAuthProviderLoginStatus',
  'getChannelSetup',
  'listMediaLanes',
  'listMediaAssets',
  'readMediaAsset',
  'resolveMediaFile',
  'getMediaJob',
  'getMediaDefault',
] as const satisfies ReadonlyArray<DesktopCapability>;

export type DesktopReadCapability = (typeof DESKTOP_READ_CAPABILITIES)[number];

export interface DesktopCapabilityRequest {
  capability: DesktopCapability;
  args?: unknown[];
  /** The session the SURFACE that issued this command is painting. Focus
   *  decides nothing: a queue ×, /clear or /compact belongs to the session
   *  its own surface shows, not to whichever pane holds the caret. */
  sessionId?: string;
}

export interface DesktopCapabilityReadRequest {
  capability: DesktopReadCapability;
  args?: unknown[];
  sessionId?: string;
}

export type DesktopCapabilityReadResult = { ok: true; value: unknown } | { ok: false; error: string };

export interface DesktopCapabilityResult<T = unknown> {
  value: T;
  snapshot: SessionSnapshot;
}
