// GENERATED FILE — do not edit by hand: run scripts/generate-editor-languages.mjs.
// Built-in language contributions resolved onto Monaco pane languages.

export type EditorLanguageClassification = "native" | "compatible" | "custom" | "plaintext";
export interface EditorLanguageDecision {
  target: string;
  classification: EditorLanguageClassification;
}
export interface EditorLanguagePattern {
  pattern: string;
  scope: "name" | "path";
  languageId: string;
  regex: RegExp;
}

export const EDITOR_LANGUAGE_AUDIT = {
  "sourceLanguageIds": 74,
  "sourceExtensions": 342,
  "sourceFileNames": 71,
  "sourcePatterns": 26,
  "runtimeExtensionKeys": 337,
  "runtimeFileNames": 75,
  "runtimePatternRules": 27,
  "classifications": {
    "native": 38,
    "plaintext": 12,
    "compatible": 23,
    "custom": 1
  }
} as const;

export const EDITOR_LANGUAGE_DECISIONS: Readonly<Record<string, EditorLanguageDecision>> = {
  "bat": {"target":"bat","classification":"native"},
  "bibtex": {"target":"plaintext","classification":"plaintext"},
  "c": {"target":"c","classification":"native"},
  "chatagent": {"target":"markdown","classification":"compatible"},
  "clojure": {"target":"clojure","classification":"native"},
  "coffeescript": {"target":"coffeescript","classification":"native"},
  "cpp": {"target":"cpp","classification":"native"},
  "cpp_embedded_latex": {"target":"plaintext","classification":"plaintext"},
  "csharp": {"target":"csharp","classification":"native"},
  "css": {"target":"css","classification":"native"},
  "cuda-cpp": {"target":"cpp","classification":"compatible"},
  "dart": {"target":"dart","classification":"native"},
  "diff": {"target":"plaintext","classification":"plaintext"},
  "dockercompose": {"target":"yaml","classification":"compatible"},
  "dockerfile": {"target":"dockerfile","classification":"native"},
  "dotenv": {"target":"ini","classification":"compatible"},
  "fsharp": {"target":"fsharp","classification":"native"},
  "git-commit": {"target":"plaintext","classification":"plaintext"},
  "git-rebase": {"target":"plaintext","classification":"plaintext"},
  "go": {"target":"go","classification":"native"},
  "groovy": {"target":"java","classification":"compatible"},
  "handlebars": {"target":"handlebars","classification":"native"},
  "hlsl": {"target":"cpp","classification":"compatible"},
  "html": {"target":"html","classification":"native"},
  "ignore": {"target":"plaintext","classification":"plaintext"},
  "ini": {"target":"ini","classification":"native"},
  "instructions": {"target":"markdown","classification":"compatible"},
  "jade": {"target":"pug","classification":"compatible"},
  "java": {"target":"java","classification":"native"},
  "javascript": {"target":"javascript","classification":"native"},
  "javascriptreact": {"target":"javascript","classification":"compatible"},
  "json": {"target":"json","classification":"native"},
  "jsonc": {"target":"json","classification":"compatible"},
  "jsonl": {"target":"json","classification":"compatible"},
  "jsx-tags": {"target":"plaintext","classification":"plaintext"},
  "julia": {"target":"julia","classification":"native"},
  "juliamarkdown": {"target":"markdown","classification":"compatible"},
  "latex": {"target":"plaintext","classification":"plaintext"},
  "less": {"target":"less","classification":"native"},
  "log": {"target":"log","classification":"custom"},
  "lua": {"target":"lua","classification":"native"},
  "makefile": {"target":"shell","classification":"compatible"},
  "markdown": {"target":"markdown","classification":"native"},
  "markdown-math": {"target":"plaintext","classification":"plaintext"},
  "markdown_latex_combined": {"target":"plaintext","classification":"plaintext"},
  "objective-c": {"target":"objective-c","classification":"native"},
  "objective-cpp": {"target":"cpp","classification":"compatible"},
  "perl": {"target":"perl","classification":"native"},
  "php": {"target":"php","classification":"native"},
  "powershell": {"target":"powershell","classification":"native"},
  "prompt": {"target":"markdown","classification":"compatible"},
  "properties": {"target":"ini","classification":"compatible"},
  "python": {"target":"python","classification":"native"},
  "r": {"target":"r","classification":"native"},
  "raku": {"target":"perl","classification":"compatible"},
  "razor": {"target":"razor","classification":"native"},
  "restructuredtext": {"target":"restructuredtext","classification":"native"},
  "ruby": {"target":"ruby","classification":"native"},
  "rust": {"target":"rust","classification":"native"},
  "scss": {"target":"scss","classification":"native"},
  "search-result": {"target":"plaintext","classification":"plaintext"},
  "shaderlab": {"target":"cpp","classification":"compatible"},
  "shellscript": {"target":"shell","classification":"compatible"},
  "skill": {"target":"markdown","classification":"compatible"},
  "snippets": {"target":"json","classification":"compatible"},
  "sql": {"target":"sql","classification":"native"},
  "swift": {"target":"swift","classification":"native"},
  "tex": {"target":"plaintext","classification":"plaintext"},
  "typescript": {"target":"typescript","classification":"native"},
  "typescriptreact": {"target":"typescript","classification":"compatible"},
  "vb": {"target":"vb","classification":"native"},
  "xml": {"target":"xml","classification":"native"},
  "xsl": {"target":"xml","classification":"compatible"},
  "yaml": {"target":"yaml","classification":"native"},
};

export const EDITOR_LANGUAGE_EXTENSIONS: Readonly<Record<string, string>> = {
  "agent.md": "markdown",
  "ascx": "xml",
  "asp": "html",
  "aspx": "html",
  "atom": "xml",
  "axaml": "xml",
  "axml": "xml",
  "babelrc": "json",
  "bas": "vb",
  "bash": "shell",
  "bash_aliases": "shell",
  "bash_login": "shell",
  "bash_logout": "shell",
  "bash_profile": "shell",
  "bashrc": "shell",
  "bat": "bat",
  "bbx": "plaintext",
  "bib": "plaintext",
  "bowerrc": "json",
  "bpmn": "xml",
  "brs": "vb",
  "c": "c",
  "c++": "cpp",
  "c++m": "cpp",
  "cake": "csharp",
  "cbx": "plaintext",
  "cc": "cpp",
  "ccm": "cpp",
  "cff": "yaml",
  "cfg": "ini",
  "cginc": "cpp",
  "chatmode.md": "markdown",
  "cjs": "javascript",
  "clj": "clojure",
  "cljc": "clojure",
  "cljs": "clojure",
  "cljx": "clojure",
  "clojure": "clojure",
  "cls": "plaintext",
  "cmd": "bat",
  "code-profile": "json",
  "code-search": "plaintext",
  "code-snippets": "json",
  "code-workspace": "json",
  "coffee": "coffeescript",
  "compute": "cpp",
  "conf": "ini",
  "containerfile": "dockerfile",
  "copilotmd": "markdown",
  "cpp": "cpp",
  "cppm": "cpp",
  "cpt": "xml",
  "cpy": "python",
  "cs": "csharp",
  "csh": "shell",
  "cshrc": "shell",
  "cshtml": "razor",
  "csl": "xml",
  "cson": "coffeescript",
  "csproj": "xml",
  "csproj.user": "xml",
  "css": "css",
  "css.map": "json",
  "csx": "csharp",
  "ctp": "php",
  "cts": "typescript",
  "ctx": "plaintext",
  "cu": "cpp",
  "cuh": "cpp",
  "cxx": "cpp",
  "cxxm": "cpp",
  "dart": "dart",
  "diff": "plaintext",
  "directory": "ini",
  "dita": "xml",
  "ditamap": "xml",
  "dockerfile": "dockerfile",
  "dsql": "sql",
  "dtd": "xml",
  "dtml": "xml",
  "ebuild": "shell",
  "eclass": "shell",
  "editorconfig": "ini",
  "edn": "clojure",
  "ejs": "html",
  "ent": "xml",
  "env": "ini",
  "erb": "ruby",
  "es6": "javascript",
  "eslintrc": "json",
  "eslintrc.json": "json",
  "eyaml": "yaml",
  "eyml": "yaml",
  "fish": "shell",
  "fs": "fsharp",
  "fsi": "fsharp",
  "fsproj": "xml",
  "fsscript": "fsharp",
  "fsx": "fsharp",
  "fx": "cpp",
  "fxh": "cpp",
  "fxml": "xml",
  "gemspec": "ruby",
  "geojson": "json",
  "git-blame-ignore-revs": "plaintext",
  "gitattributes": "ini",
  "gitconfig": "ini",
  "gitignore": "plaintext",
  "gitignore_global": "plaintext",
  "gitmodules": "ini",
  "go": "go",
  "gradle": "java",
  "groovy": "java",
  "gvy": "java",
  "gyp": "python",
  "gypi": "python",
  "h": "cpp",
  "h.in": "cpp",
  "h++": "cpp",
  "handlebars": "handlebars",
  "har": "json",
  "hbs": "handlebars",
  "hh": "cpp",
  "hintrc": "json",
  "hjs": "handlebars",
  "hlsl": "cpp",
  "hlsli": "cpp",
  "hpp": "cpp",
  "hpp.in": "cpp",
  "htm": "html",
  "html": "html",
  "hxx": "cpp",
  "i": "c",
  "iced": "coffeescript",
  "ii": "cpp",
  "iml": "xml",
  "ini": "ini",
  "inl": "cpp",
  "ino": "cpp",
  "instructions.md": "markdown",
  "ipp": "cpp",
  "ipy": "python",
  "ipynb": "json",
  "isml": "xml",
  "ixx": "cpp",
  "jade": "pug",
  "jav": "java",
  "java": "java",
  "jenkinsfile": "java",
  "jl": "julia",
  "jmd": "markdown",
  "jmx": "xml",
  "js": "javascript",
  "js.map": "json",
  "jscsrc": "json",
  "jsfmtrc": "json",
  "jshintrc": "json",
  "jshtm": "html",
  "jslintrc": "json",
  "json": "json",
  "jsonc": "json",
  "jsonl": "json",
  "jsonld": "json",
  "jsp": "html",
  "jsx": "javascript",
  "ksh": "shell",
  "launch": "xml",
  "less": "less",
  "litcoffee": "markdown",
  "log": "log",
  "ltx": "plaintext",
  "lua": "lua",
  "m": "objective-c",
  "mak": "shell",
  "markdn": "markdown",
  "markdown": "markdown",
  "md": "markdown",
  "mdoc": "html",
  "mdown": "markdown",
  "mdtext": "markdown",
  "mdtxt": "markdown",
  "mdwn": "markdown",
  "menu": "xml",
  "mjs": "javascript",
  "mk": "shell",
  "mkd": "markdown",
  "mkdn": "markdown",
  "mm": "cpp",
  "mod": "xml",
  "mpp": "cpp",
  "mts": "typescript",
  "mxml": "xml",
  "mxx": "cpp",
  "ndjson": "json",
  "nf": "java",
  "npmignore": "plaintext",
  "npmrc": "ini",
  "nqp": "perl",
  "nuspec": "xml",
  "opml": "xml",
  "owl": "xml",
  "p6": "perl",
  "pac": "javascript",
  "patch": "plaintext",
  "php": "php",
  "php4": "php",
  "php5": "php",
  "phtml": "php",
  "pl": "perl",
  "pl6": "perl",
  "pm": "perl",
  "pm6": "perl",
  "pod": "perl",
  "podspec": "ruby",
  "profile": "shell",
  "proj": "xml",
  "prompt.md": "markdown",
  "properties": "ini",
  "props": "xml",
  "ps1": "powershell",
  "psd1": "powershell",
  "psgi": "perl",
  "psh": "cpp",
  "psm1": "powershell",
  "psrc": "powershell",
  "pssc": "powershell",
  "pt": "xml",
  "publishsettings": "xml",
  "pubxml": "xml",
  "pubxml.user": "xml",
  "pug": "pug",
  "py": "python",
  "pyi": "python",
  "pyt": "python",
  "pyw": "python",
  "r": "r",
  "rake": "ruby",
  "raku": "perl",
  "rakudoc": "perl",
  "rakumod": "perl",
  "rakutest": "perl",
  "razor": "razor",
  "rb": "ruby",
  "rbi": "ruby",
  "rbx": "ruby",
  "rbxlx": "xml",
  "rbxmx": "xml",
  "rdf": "xml",
  "rej": "plaintext",
  "repo": "ini",
  "rhistory": "r",
  "rhtml": "html",
  "rjs": "ruby",
  "rng": "xml",
  "ron": "markdown",
  "ronn": "markdown",
  "rprofile": "r",
  "rpy": "python",
  "rs": "rust",
  "rss": "xml",
  "rst": "restructuredtext",
  "rt": "r",
  "ru": "ruby",
  "scss": "scss",
  "sh": "shell",
  "shader": "cpp",
  "shproj": "xml",
  "shtml": "html",
  "slnx": "xml",
  "sql": "sql",
  "storyboard": "xml",
  "sty": "plaintext",
  "svg": "xml",
  "swcrc": "json",
  "swift": "swift",
  "t": "perl",
  "targets": "xml",
  "tcshrc": "shell",
  "tex": "plaintext",
  "tld": "xml",
  "tmx": "xml",
  "toolset.jsonc": "json",
  "tpp": "cpp",
  "ts": "typescript",
  "ts.map": "json",
  "tsbuildinfo": "json",
  "tsx": "typescript",
  "txx": "cpp",
  "vb": "vb",
  "vba": "vb",
  "vbproj": "xml",
  "vbproj.user": "xml",
  "vbs": "vb",
  "vcxproj": "xml",
  "vcxproj.filters": "xml",
  "volt": "html",
  "vsh": "cpp",
  "vuerc": "json",
  "webmanifest": "json",
  "winget": "yaml",
  "wixproj": "xml",
  "workbook": "markdown",
  "wsdl": "xml",
  "wxi": "xml",
  "wxl": "xml",
  "wxs": "xml",
  "xaml": "xml",
  "xbl": "xml",
  "xht": "html",
  "xhtml": "html",
  "xib": "xml",
  "xlf": "xml",
  "xliff": "xml",
  "xml": "xml",
  "xoml": "xml",
  "xpdl": "xml",
  "xprofile": "shell",
  "xsd": "xml",
  "xsession": "shell",
  "xsessionrc": "shell",
  "xsl": "xml",
  "xslt": "xml",
  "xul": "xml",
  "yaml": "yaml",
  "yaml-tmlanguage": "yaml",
  "yaml-tmpreferences": "yaml",
  "yaml-tmtheme": "yaml",
  "yash_profile": "shell",
  "yashrc": "shell",
  "yml": "yaml",
  "zlogin": "shell",
  "zlogout": "shell",
  "zprofile": "shell",
  "zsh": "shell",
  "zsh-theme": "shell",
  "zshenv": "shell",
  "zshrc": "shell",
};

export const EDITOR_LANGUAGE_NAMES: Readonly<Record<string, string>> = {
  ".babelrc.json": "json",
  ".devcontainer.json": "json",
  ".ember-cli": "json",
  ".env": "ini",
  ".envrc": "shell",
  ".flaskenv": "ini",
  ".hushlogin": "shell",
  ".vscodeignore": "plaintext",
  ".watchmanconfig": "json",
  "apkbuild": "shell",
  "appfile": "ruby",
  "appraisals": "ruby",
  "argv.json": "json",
  "babel.config.json": "json",
  "bashrc_apple_terminal": "shell",
  "berksfile": "ruby",
  "berksfile.lock": "ruby",
  "brewfile": "ruby",
  "bun.lock": "json",
  "capfile": "ruby",
  "cheffile": "ruby",
  "color-theme.json": "json",
  "commit_editmsg": "plaintext",
  "composer.lock": "json",
  "containerfile": "dockerfile",
  "copilot-instructions.md": "markdown",
  "dangerfile": "ruby",
  "deliverfile": "ruby",
  "devcontainer.json": "json",
  "dockerfile": "dockerfile",
  "extensions.json": "json",
  "fastfile": "ruby",
  "gemfile": "ruby",
  "git-rebase-todo": "plaintext",
  "gitconfig": "ini",
  "gnumakefile": "shell",
  "guardfile": "ruby",
  "gymfile": "ruby",
  "hobofile": "ruby",
  "icon-theme.json": "json",
  "jakefile": "javascript",
  "jenkinsfile": "java",
  "jsconfig.json": "json",
  "keybindings.json": "json",
  "language-configuration.json": "json",
  "launch.json": "json",
  "makefile": "shell",
  "matchfile": "ruby",
  "mcp.json": "json",
  "merge_msg": "plaintext",
  "ocamlmakefile": "shell",
  "pkgbuild": "shell",
  "podfile": "ruby",
  "profiles.json": "json",
  "puppetfile": "ruby",
  "rakefile": "ruby",
  "rantfile": "ruby",
  "scanfile": "ruby",
  "sconscript": "python",
  "sconstruct": "python",
  "settings.json": "json",
  "skill.md": "markdown",
  "snapfile": "ruby",
  "tasks.json": "json",
  "thorfile": "ruby",
  "tsconfig.json": "json",
  "typedoc.json": "json",
  "user-dirs.dirs": "ini",
  "vagrantfile": "ruby",
  "zlogin": "shell",
  "zlogout": "shell",
  "zprofile": "shell",
  "zshenv": "shell",
  "zshrc": "shell",
  "zshrc_apple_terminal": "shell",
};

export const EDITOR_LANGUAGE_PATTERNS: readonly EditorLanguagePattern[] = [
  { pattern: "**/.github/hooks/*.json", scope: "path", languageId: "json", regex: new RegExp("^(?:.*/)?\\.github/hooks/[^/]*\\.json$", "i") },
  { pattern: "tsconfig.*.json", scope: "name", languageId: "json", regex: new RegExp("^tsconfig\\.[^/]*\\.json$", "i") },
  { pattern: "jsconfig.*.json", scope: "name", languageId: "json", regex: new RegExp("^jsconfig\\.[^/]*\\.json$", "i") },
  { pattern: "tsconfig-*.json", scope: "name", languageId: "json", regex: new RegExp("^tsconfig-[^/]*\\.json$", "i") },
  { pattern: "jsconfig-*.json", scope: "name", languageId: "json", regex: new RegExp("^jsconfig-[^/]*\\.json$", "i") },
  { pattern: ".copilotignore", scope: "name", languageId: "plaintext", regex: new RegExp("^\\.copilotignore$", "i") },
  { pattern: "**/.cursor/**/*.mdc", scope: "path", languageId: "markdown", regex: new RegExp("^(?:.*/)?\\.cursor/(?:.*/)?[^/]*\\.mdc$", "i") },
  { pattern: "dockerfile.*", scope: "name", languageId: "dockerfile", regex: new RegExp("^dockerfile\\.[^/]*$", "i") },
  { pattern: "containerfile.*", scope: "name", languageId: "dockerfile", regex: new RegExp("^containerfile\\.[^/]*$", "i") },
  { pattern: ".env.*", scope: "name", languageId: "ini", regex: new RegExp("^\\.env\\.[^/]*$", "i") },
  { pattern: "**/rebase-merge/done", scope: "path", languageId: "plaintext", regex: new RegExp("^(?:.*/)?rebase-merge/done$", "i") },
  { pattern: "jenkinsfile*", scope: "name", languageId: "java", regex: new RegExp("^jenkinsfile[^/]*$", "i") },
  { pattern: "**/.config/git/config", scope: "path", languageId: "ini", regex: new RegExp("^(?:.*/)?\\.config/git/config$", "i") },
  { pattern: "**/.git/config", scope: "path", languageId: "ini", regex: new RegExp("^(?:.*/)?\\.git/config$", "i") },
  { pattern: "**/user/snippets/*.json", scope: "path", languageId: "json", regex: new RegExp("^(?:.*/)?user/snippets/[^/]*\\.json$", "i") },
  { pattern: "**/user/profiles/*/snippets/*.json", scope: "path", languageId: "json", regex: new RegExp("^(?:.*/)?user/profiles/[^/]*/snippets/[^/]*\\.json$", "i") },
  { pattern: "**/snippets*.json", scope: "path", languageId: "json", regex: new RegExp("^(?:.*/)?snippets[^/]*\\.json$", "i") },
  { pattern: "*.log.?", scope: "name", languageId: "log", regex: new RegExp("^[^/]*\\.log\\.[^/]$", "i") },
  { pattern: "**/.claude/rules/**/*.md", scope: "path", languageId: "markdown", regex: new RegExp("^(?:.*/)?\\.claude/rules/(?:.*/)?[^/]*\\.md$", "i") },
  { pattern: "**/.github/agents/*.md", scope: "path", languageId: "markdown", regex: new RegExp("^(?:.*/)?\\.github/agents/[^/]*\\.md$", "i") },
  { pattern: "**/.claude/agents/*.md", scope: "path", languageId: "markdown", regex: new RegExp("^(?:.*/)?\\.claude/agents/[^/]*\\.md$", "i") },
  { pattern: "compose.yml", scope: "name", languageId: "yaml", regex: new RegExp("^compose\\.yml$", "i") },
  { pattern: "compose.yaml", scope: "name", languageId: "yaml", regex: new RegExp("^compose\\.yaml$", "i") },
  { pattern: "compose.*.yml", scope: "name", languageId: "yaml", regex: new RegExp("^compose\\.[^/]*\\.yml$", "i") },
  { pattern: "compose.*.yaml", scope: "name", languageId: "yaml", regex: new RegExp("^compose\\.[^/]*\\.yaml$", "i") },
  { pattern: "*docker*compose*.yml", scope: "name", languageId: "yaml", regex: new RegExp("^[^/]*docker[^/]*compose[^/]*\\.yml$", "i") },
  { pattern: "*docker*compose*.yaml", scope: "name", languageId: "yaml", regex: new RegExp("^[^/]*docker[^/]*compose[^/]*\\.yaml$", "i") },
];

export function explicitEditorLanguageIdForPath(path: string): string | undefined {
  const normalized = String(path || "").replace(/\\/g, "/").toLowerCase();
  const base = normalized.slice(normalized.lastIndexOf("/") + 1);
  const named = EDITOR_LANGUAGE_NAMES[base];
  if (named) return named;
  for (const rule of EDITOR_LANGUAGE_PATTERNS) {
    const candidate = rule.scope === "path" ? normalized : base;
    if (rule.regex.test(candidate)) return rule.languageId;
  }
  const parts = base.split(".");
  for (let index = 0; index < parts.length; index += 1) {
    const suffix = parts.slice(index).join(".").replace(/^\./, "");
    const languageId = EDITOR_LANGUAGE_EXTENSIONS[suffix];
    if (languageId) return languageId;
  }
  return undefined;
}

export function editorLanguageIdForPath(path: string): string {
  return explicitEditorLanguageIdForPath(path) || "plaintext";
}
