export const DESKTOP_SIDEBAR_MIN_WIDTH = 232;
export const DESKTOP_WORKSPACE_MIN_WIDTH = 360;
export const DESKTOP_UTILITY_DOCK_MIN_WIDTH = 300;

const DESKTOP_BODY_HORIZONTAL_PADDING = 16;
const DESKTOP_PANEL_GAP = 8;

export const DESKTOP_WINDOW_MIN_WIDTH =
  DESKTOP_SIDEBAR_MIN_WIDTH
  + DESKTOP_WORKSPACE_MIN_WIDTH
  + DESKTOP_UTILITY_DOCK_MIN_WIDTH
  + DESKTOP_BODY_HORIZONTAL_PADDING
  + (DESKTOP_PANEL_GAP * 2);
