// GENERATED FILE — do not edit by hand: run scripts/generate-seti-icons.mjs.
// Attribution and license details live in LICENSES/editor-assets-NOTICE.txt.
// See THIRD-PARTY-NOTICES.txt. Dark-theme colour set.

export const SETI_DEFAULT_ID = "_default";

export const SETI_ICON_DEFS: Record<string, readonly [string, string]> = {
  "_windows": ["\uE0A2", "#519aba"],
  "_clojure": ["\uE013", "#8dc149"],
  "_coffee": ["\uE016", "#cbcb41"],
  "_json": ["\uE055", "#cbcb41"],
  "_git": ["\uE034", "#41535b"],
  "_markdown": ["\uE060", "#519aba"],
  "_c": ["\uE00C", "#519aba"],
  "_cpp": ["\uE01A", "#519aba"],
  "_cu": ["\uE01F", "#8dc149"],
  "_c-sharp": ["\uE00B", "#519aba"],
  "_css": ["\uE01D", "#519aba"],
  "_dart": ["\uE021", "#519aba"],
  "_docker": ["\uE025", "#519aba"],
  "_config": ["\uE019", "#6d8086"],
  "_f-sharp": ["\uE02E", "#519aba"],
  "_go2": ["\uE03A", "#519aba"],
  "_grails": ["\uE03D", "#8dc149"],
  "_mustache": ["\uE063", "#e37933"],
  "_html_3": ["\uE048", "#e37933"],
  "_java": ["\uE050", "#cc3e44"],
  "_react": ["\uE07D", "#519aba"],
  "_javascript": ["\uE051", "#cbcb41"],
  "_julia": ["\uE056", "#a074c4"],
  "_tex_1": ["\uE094", "#cbcb41"],
  "_tex": ["\uE094", "#519aba"],
  "_less": ["\uE059", "#519aba"],
  "_lua": ["\uE05E", "#519aba"],
  "_makefile": ["\uE05F", "#e37933"],
  "_c_2": ["\uE00C", "#cbcb41"],
  "_cpp_2": ["\uE01A", "#cbcb41"],
  "_perl": ["\uE06E", "#519aba"],
  "_php": ["\uE070", "#a074c4"],
  "_powershell": ["\uE074", "#519aba"],
  "_pug": ["\uE078", "#cc3e44"],
  "_python": ["\uE07B", "#519aba"],
  "_R": ["\uE001", "#519aba"],
  "_html": ["\uE048", "#519aba"],
  "_ruby": ["\uE081", "#cc3e44"],
  "_rust": ["\uE082", "#6d8086"],
  "_sass": ["\uE084", "#f55385"],
  "_code-search": ["\uE015", "#a074c4"],
  "_shell": ["\uE089", "#8dc149"],
  "_db": ["\uE022", "#f55385"],
  "_swift": ["\uE092", "#e37933"],
  "_typescript": ["\uE099", "#519aba"],
  "_xml": ["\uE0A5", "#e37933"],
  "_docker_3": ["\uE025", "#f55385"],
  "_yml": ["\uE0A7", "#a074c4"],
  "_bsl": ["\uE00A", "#cc3e44"],
  "_mdo": ["\uE062", "#cc3e44"],
  "_salesforce": ["\uE083", "#519aba"],
  "_asm": ["\uE004", "#cc3e44"],
  "_bicep": ["\uE008", "#519aba"],
  "_bazel": ["\uE007", "#8dc149"],
  "_c_1": ["\uE00C", "#a074c4"],
  "_html_1": ["\uE048", "#8dc149"],
  "_html_2": ["\uE048", "#cbcb41"],
  "_cpp_1": ["\uE01A", "#a074c4"],
  "_clojure_1": ["\uE013", "#519aba"],
  "_coldfusion": ["\uE018", "#519aba"],
  "_crystal": ["\uE01B", "#d4d7d6"],
  "_crystal_embedded": ["\uE01C", "#d4d7d6"],
  "_csv": ["\uE01E", "#8dc149"],
  "_xls": ["\uE0A4", "#8dc149"],
  "_cu_1": ["\uE01F", "#a074c4"],
  "_cake": ["\uE00D", "#cc3e44"],
  "_cake_php": ["\uE00E", "#cc3e44"],
  "_d": ["\uE020", "#cc3e44"],
  "_word": ["\uE0A3", "#519aba"],
  "_ejs": ["\uE027", "#cbcb41"],
  "_elixir": ["\uE028", "#a074c4"],
  "_elixir_script": ["\uE029", "#a074c4"],
  "_elm": ["\uE02A", "#519aba"],
  "_favicon": ["\uE02F", "#cbcb41"],
  "_go": ["\uE039", "#519aba"],
  "_godot": ["\uE03B", "#519aba"],
  "_godot_1": ["\uE03B", "#cc3e44"],
  "_godot_2": ["\uE03B", "#cbcb41"],
  "_godot_3": ["\uE03B", "#a074c4"],
  "_gradle": ["\uE03C", "#519aba"],
  "_graphql": ["\uE03E", "#f55385"],
  "_hacklang": ["\uE041", "#e37933"],
  "_haml": ["\uE042", "#cc3e44"],
  "_haskell": ["\uE044", "#a074c4"],
  "_haxe": ["\uE045", "#e37933"],
  "_haxe_1": ["\uE045", "#cbcb41"],
  "_haxe_2": ["\uE045", "#519aba"],
  "_haxe_3": ["\uE045", "#a074c4"],
  "_jade": ["\uE04F", "#cc3e44"],
  "_java_1": ["\uE050", "#519aba"],
  "_javascript_1": ["\uE051", "#e37933"],
  "_jinja": ["\uE053", "#cc3e44"],
  "_kotlin": ["\uE058", "#e37933"],
  "_liquid": ["\uE05B", "#8dc149"],
  "_livescript": ["\uE05C", "#519aba"],
  "_argdown": ["\uE003", "#519aba"],
  "_nim": ["\uE065", "#cbcb41"],
  "_github": ["\uE037", "#d4d7d6"],
  "_notebook": ["\uE066", "#519aba"],
  "_nunjucks": ["\uE069", "#8dc149"],
  "_npm": ["\uE067", "#41535b"],
  "_npm_1": ["\uE067", "#cc3e44"],
  "_ocaml": ["\uE06A", "#e37933"],
  "_odata": ["\uE06B", "#e37933"],
  "_pipeline": ["\uE071", "#e37933"],
  "_pddl": ["\uE06C", "#a074c4"],
  "_plan": ["\uE072", "#8dc149"],
  "_happenings": ["\uE043", "#519aba"],
  "_prisma": ["\uE075", "#519aba"],
  "_puppet": ["\uE079", "#cbcb41"],
  "_purescript": ["\uE07A", "#d4d7d6"],
  "_react_1": ["\uE07D", "#e37933"],
  "_reasonml": ["\uE07E", "#cc3e44"],
  "_rescript": ["\uE07F", "#cc3e44"],
  "_rescript_1": ["\uE07F", "#f55385"],
  "_html_erb": ["\uE049", "#cc3e44"],
  "_spring": ["\uE08C", "#8dc149"],
  "_slim": ["\uE08A", "#e37933"],
  "_smarty": ["\uE08B", "#cbcb41"],
  "_sbt": ["\uE085", "#519aba"],
  "_scala": ["\uE086", "#cc3e44"],
  "_ethereum": ["\uE02D", "#519aba"],
  "_stylus": ["\uE08E", "#8dc149"],
  "_svelte": ["\uE090", "#cc3e44"],
  "_db_1": ["\uE022", "#519aba"],
  "_terraform": ["\uE093", "#a074c4"],
  "_tex_2": ["\uE094", "#e37933"],
  "_tex_3": ["\uE094", "#d4d7d6"],
  "_twig": ["\uE098", "#8dc149"],
  "_typescript_1": ["\uE099", "#e37933"],
  "_vala": ["\uE09A", "#6d8086"],
  "_vue": ["\uE09D", "#8dc149"],
  "_wasm": ["\uE09E", "#a074c4"],
  "_wat": ["\uE09F", "#a074c4"],
  "_prolog": ["\uE077", "#e37933"],
  "_zig": ["\uE0A8", "#e37933"],
  "_zip": ["\uE0A9", "#cc3e44"],
  "_zip_1": ["\uE0A9", "#6d8086"],
  "_wgt": ["\uE0A1", "#519aba"],
  "_illustrator": ["\uE04B", "#cbcb41"],
  "_photoshop": ["\uE06F", "#519aba"],
  "_pdf": ["\uE06D", "#cc3e44"],
  "_font": ["\uE033", "#cc3e44"],
  "_image": ["\uE04C", "#a074c4"],
  "_svg": ["\uE091", "#a074c4"],
  "_sublime": ["\uE08F", "#e37933"],
  "_video": ["\uE09B", "#f55385"],
  "_audio": ["\uE005", "#a074c4"],
  "_svg_1": ["\uE091", "#519aba"],
  "_babel": ["\uE006", "#cbcb41"],
  "_bazel_1": ["\uE007", "#4d5a5e"],
  "_bower": ["\uE009", "#e37933"],
  "_docker_1": ["\uE025", "#4d5a5e"],
  "_code-climate": ["\uE014", "#8dc149"],
  "_eslint": ["\uE02C", "#a074c4"],
  "_eslint_1": ["\uE02C", "#4d5a5e"],
  "_firebase": ["\uE030", "#e37933"],
  "_gitlab": ["\uE038", "#e37933"],
  "_javascript_2": ["\uE051", "#519aba"],
  "_stylelint": ["\uE08D", "#d4d7d6"],
  "_stylelint_1": ["\uE08D", "#4d5a5e"],
  "_clock_1": ["\uE012", "#6d8086"],
  "_lock": ["\uE05D", "#8dc149"],
  "_ignored": ["\uE04A", "#41535b"],
  "_hex": ["\uE047", "#cc3e44"],
  "_karma": ["\uE057", "#8dc149"],
  "_info": ["\uE04D", "#519aba"],
  "_clock": ["\uE012", "#519aba"],
  "_maven": ["\uE061", "#cc3e44"],
  "_tsconfig": ["\uE097", "#519aba"],
  "_vite": ["\uE09C", "#cbcb41"],
  "_json_1": ["\uE055", "#8dc149"],
  "_jenkins": ["\uE052", "#cc3e44"],
  "_docker_2": ["\uE025", "#8dc149"],
  "_firefox": ["\uE031", "#e37933"],
  "_grunt": ["\uE03F", "#e37933"],
  "_gulp": ["\uE040", "#cc3e44"],
  "_ionic": ["\uE04E", "#519aba"],
  "_platformio": ["\uE073", "#e37933"],
  "_rollup": ["\uE080", "#cc3e44"],
  "_yarn": ["\uE0A6", "#519aba"],
  "_webpack": ["\uE0A0", "#519aba"],
  "_license": ["\uE05A", "#cbcb41"],
  "_license_1": ["\uE05A", "#e37933"],
  "_license_2": ["\uE05A", "#cc3e44"],
  "_makefile_1": ["\uE05F", "#a074c4"],
  "_makefile_2": ["\uE05F", "#6d8086"],
  "_makefile_3": ["\uE05F", "#519aba"],
  "_heroku": ["\uE046", "#a074c4"],
  "_todo": ["\uE096", ""],
  "_npm_ignored": ["\uE068", "#41535b"],
  "_default": ["\uE023", "#d4d7d6"],
};

export const SETI_FILE_EXTENSIONS: Record<string, string> = {
  "bat": "_windows",
  "cmd": "_windows",
  "clj": "_clojure",
  "cljs": "_clojure",
  "cljc": "_clojure",
  "cljx": "_clojure",
  "clojure": "_clojure",
  "edn": "_clojure_1",
  "coffee": "_coffee",
  "cson": "_json",
  "iced": "_coffee",
  "code-workspace": "_json",
  "language-configuration.json": "_json",
  "icon-theme.json": "_json",
  "color-theme.json": "_json",
  "code-profile": "_json",
  "copilotmd": "_markdown",
  "c": "_c",
  "i": "_c",
  "cpp": "_cpp",
  "cppm": "_cpp",
  "cc": "_cpp",
  "ccm": "_cpp",
  "cxx": "_cpp",
  "cxxm": "_cpp",
  "c++": "_cpp",
  "c++m": "_cpp",
  "hpp": "_cpp_1",
  "hh": "_cpp_1",
  "hxx": "_cpp_1",
  "h++": "_cpp_1",
  "h": "_c_1",
  "ii": "_cpp",
  "ino": "_cpp",
  "inl": "_cpp",
  "ipp": "_cpp",
  "ixx": "_cpp",
  "mpp": "_cpp",
  "mxx": "_cpp",
  "tpp": "_cpp",
  "txx": "_cpp",
  "hpp.in": "_cpp",
  "h.in": "_cpp",
  "cu": "_cu",
  "cuh": "_cu_1",
  "cs": "_c-sharp",
  "csx": "_c-sharp",
  "cake": "_cake",
  "css": "_css",
  "dart": "_dart",
  "dockerfile": "_docker",
  "containerfile": "_docker",
  "env": "_config",
  "fs": "_f-sharp",
  "fsi": "_f-sharp",
  "fsx": "_f-sharp",
  "fsscript": "_f-sharp",
  "gitignore_global": "_git",
  "gitignore": "_git",
  "git-blame-ignore-revs": "_git",
  "go": "_go2",
  "groovy": "_grails",
  "gvy": "_grails",
  "gradle": "_gradle",
  "jenkinsfile": "_grails",
  "nf": "_grails",
  "handlebars": "_mustache",
  "hbs": "_mustache",
  "hjs": "_mustache",
  "html": "_html_3",
  "htm": "_html_3",
  "shtml": "_html_3",
  "xhtml": "_html_3",
  "xht": "_html_3",
  "mdoc": "_html_3",
  "jsp": "_html_3",
  "asp": "_html_3",
  "aspx": "_html",
  "jshtm": "_html_3",
  "volt": "_html_3",
  "ejs": "_ejs",
  "rhtml": "_html_3",
  "conf": "_config",
  "properties": "_config",
  "cfg": "_config",
  "directory": "_config",
  "gitattributes": "_git",
  "gitconfig": "_git",
  "gitmodules": "_git",
  "editorconfig": "_config",
  "repo": "_config",
  "java": "_java",
  "jav": "_java",
  "jsx": "_react",
  "js": "_javascript",
  "es6": "_javascript",
  "mjs": "_javascript",
  "cjs": "_javascript",
  "pac": "_javascript",
  "json": "_json",
  "bowerrc": "_bower",
  "jscsrc": "_javascript_2",
  "webmanifest": "_json",
  "js.map": "_javascript",
  "css.map": "_css",
  "ts.map": "_json",
  "har": "_json",
  "jslintrc": "_json",
  "jsonld": "_json",
  "geojson": "_json",
  "ipynb": "_notebook",
  "vuerc": "_json",
  "jsonc": "_json",
  "eslintrc": "_eslint",
  "eslintrc.json": "_eslint",
  "jsfmtrc": "_json",
  "jshintrc": "_javascript_2",
  "swcrc": "_json",
  "hintrc": "_json",
  "babelrc": "_babel",
  "toolset.jsonc": "_json",
  "jsonl": "_json",
  "ndjson": "_json",
  "jl": "_julia",
  "sty": "_tex_1",
  "cls": "_salesforce",
  "bbx": "_tex_1",
  "cbx": "_tex_1",
  "tex": "_tex",
  "ltx": "_tex",
  "ctx": "_tex",
  "less": "_less",
  "lua": "_lua",
  "mak": "_makefile",
  "mk": "_makefile",
  "md": "_markdown",
  "mkd": "_markdown",
  "mkdn": "_markdown",
  "mdwn": "_markdown",
  "mdown": "_markdown",
  "markdown": "_markdown",
  "markdn": "_markdown",
  "mdtxt": "_markdown",
  "mdtext": "_markdown",
  "litcoffee": "_coffee",
  "ron": "_markdown",
  "ronn": "_markdown",
  "workbook": "_markdown",
  "npmignore": "_npm_1",
  "npmrc": "_npm_1",
  "m": "_c_2",
  "mm": "_cpp_2",
  "pl": "_perl",
  "pm": "_perl",
  "pod": "_perl",
  "t": "_perl",
  "psgi": "_perl",
  "php": "_php",
  "php4": "_php",
  "php5": "_php",
  "phtml": "_php",
  "ctp": "_cake_php",
  "ps1": "_powershell",
  "psm1": "_powershell",
  "psd1": "_powershell",
  "pssc": "_powershell",
  "psrc": "_powershell",
  "prompt.md": "_markdown",
  "instructions.md": "_markdown",
  "copilot-instructions.md": "_markdown",
  "agent.md": "_markdown",
  "chatmode.md": "_markdown",
  "pug": "_pug",
  "jade": "_jade",
  "py": "_python",
  "rpy": "_python",
  "pyw": "_python",
  "cpy": "_python",
  "gyp": "_python",
  "gypi": "_python",
  "pyi": "_python",
  "ipy": "_python",
  "pyt": "_python",
  "r": "_R",
  "rhistory": "_R",
  "rprofile": "_R",
  "rt": "_R",
  "cshtml": "_html",
  "razor": "_html",
  "rb": "_ruby",
  "rbx": "_ruby",
  "rjs": "_ruby",
  "gemspec": "_ruby",
  "rake": "_ruby",
  "ru": "_ruby",
  "erb": "_html_erb",
  "podspec": "_ruby",
  "rbi": "_ruby",
  "rs": "_rust",
  "scss": "_sass",
  "code-search": "_code-search",
  "sh": "_shell",
  "bash": "_shell",
  "bashrc": "_shell",
  "bash_aliases": "_shell",
  "bash_profile": "_shell",
  "bash_login": "_shell",
  "ebuild": "_shell",
  "eclass": "_shell",
  "profile": "_shell",
  "bash_logout": "_shell",
  "xprofile": "_shell",
  "xsession": "_shell",
  "xsessionrc": "_shell",
  "zsh": "_shell",
  "zshrc": "_shell",
  "zprofile": "_shell",
  "zlogin": "_shell",
  "zlogout": "_shell",
  "zshenv": "_shell",
  "zsh-theme": "_shell",
  "fish": "_shell",
  "ksh": "_shell",
  "csh": "_shell",
  "cshrc": "_shell",
  "tcshrc": "_shell",
  "yashrc": "_shell",
  "yash_profile": "_shell",
  "sql": "_db",
  "dsql": "_db",
  "swift": "_swift",
  "ts": "_typescript",
  "cts": "_typescript",
  "mts": "_typescript",
  "tsx": "_react",
  "tsbuildinfo": "_json",
  "xml": "_xml",
  "xsd": "_xml",
  "ascx": "_html_1",
  "atom": "_xml",
  "axml": "_xml",
  "axaml": "_xml",
  "bpmn": "_xml",
  "cpt": "_xml",
  "csl": "_xml",
  "csproj": "_xml",
  "csproj.user": "_xml",
  "dita": "_xml",
  "ditamap": "_xml",
  "dtd": "_xml",
  "ent": "_xml",
  "mod": "_xml",
  "dtml": "_xml",
  "fsproj": "_xml",
  "fxml": "_xml",
  "iml": "_xml",
  "isml": "_xml",
  "jmx": "_xml",
  "launch": "_xml",
  "menu": "_xml",
  "mxml": "_xml",
  "nuspec": "_xml",
  "opml": "_xml",
  "owl": "_xml",
  "proj": "_xml",
  "props": "_xml",
  "pt": "_xml",
  "publishsettings": "_xml",
  "pubxml": "_xml",
  "pubxml.user": "_xml",
  "rbxlx": "_xml",
  "rbxmx": "_xml",
  "rdf": "_xml",
  "rng": "_xml",
  "rss": "_xml",
  "shproj": "_xml",
  "slnx": "_xml",
  "storyboard": "_xml",
  "svg": "_svg",
  "targets": "_xml",
  "tld": "_xml",
  "tmx": "_xml",
  "vbproj": "_xml",
  "vbproj.user": "_xml",
  "vcxproj": "_xml",
  "vcxproj.filters": "_xml",
  "wixproj": "_xml",
  "wsdl": "_xml",
  "wxi": "_xml",
  "wxl": "_xml",
  "wxs": "_xml",
  "xaml": "_xml",
  "xbl": "_xml",
  "xib": "_xml",
  "xlf": "_xml",
  "xliff": "_xml",
  "xpdl": "_xml",
  "xul": "_xml",
  "xoml": "_xml",
  "yaml": "_yml",
  "yml": "_yml",
  "eyaml": "_yml",
  "eyml": "_yml",
  "cff": "_yml",
  "yaml-tmlanguage": "_yml",
  "yaml-tmpreferences": "_yml",
  "yaml-tmtheme": "_yml",
  "winget": "_yml",
  "bsl": "_bsl",
  "mdo": "_mdo",
  "apex": "_salesforce",
  "asm": "_asm",
  "s": "_asm",
  "bicep": "_bicep",
  "bzl": "_bazel",
  "bazel": "_bazel",
  "build": "_bazel",
  "workspace": "_bazel",
  "bazelignore": "_bazel",
  "bazelversion": "_bazel",
  "asax": "_html_2",
  "master": "_html_2",
  "cfc": "_coldfusion",
  "cfm": "_coldfusion",
  "config": "_config",
  "cr": "_crystal",
  "ecr": "_crystal_embedded",
  "slang": "_crystal_embedded",
  "sss": "_css",
  "csv": "_csv",
  "xls": "_xls",
  "xlsx": "_xls",
  "hu": "_cu_1",
  "d": "_d",
  "doc": "_word",
  "docx": "_word",
  "ex": "_elixir",
  "exs": "_elixir_script",
  "elm": "_elm",
  "ico": "_favicon",
  "gitkeep": "_git",
  "slide": "_go",
  "article": "_go",
  "gd": "_godot",
  "godot": "_godot_1",
  "tres": "_godot_2",
  "tscn": "_godot_3",
  "gsp": "_grails",
  "gql": "_graphql",
  "graphql": "_graphql",
  "graphqls": "_graphql",
  "hack": "_hacklang",
  "haml": "_haml",
  "hs": "_haskell",
  "lhs": "_haskell",
  "hx": "_haxe",
  "hxs": "_haxe_1",
  "hxp": "_haxe_2",
  "hxml": "_haxe_3",
  "class": "_java_1",
  "classpath": "_java",
  "cjs.map": "_javascript",
  "mjs.map": "_javascript",
  "spec.js": "_javascript_1",
  "spec.cjs": "_javascript_1",
  "spec.mjs": "_javascript_1",
  "test.js": "_javascript_1",
  "test.cjs": "_javascript_1",
  "test.mjs": "_javascript_1",
  "es": "_javascript",
  "es5": "_javascript",
  "es7": "_javascript",
  "jinja": "_jinja",
  "jinja2": "_jinja",
  "kt": "_kotlin",
  "kts": "_kotlin",
  "liquid": "_liquid",
  "ls": "_livescript",
  "argdown": "_argdown",
  "ad": "_argdown",
  "mustache": "_mustache",
  "stache": "_mustache",
  "nim": "_nim",
  "nims": "_nim",
  "github-issues": "_github",
  "njk": "_nunjucks",
  "nunjucks": "_nunjucks",
  "nunjs": "_nunjucks",
  "nunj": "_nunjucks",
  "njs": "_nunjucks",
  "nj": "_nunjucks",
  "npm-debug.log": "_npm",
  "ml": "_ocaml",
  "mli": "_ocaml",
  "cmx": "_ocaml",
  "cmxa": "_ocaml",
  "odata": "_odata",
  "php.inc": "_php",
  "pipeline": "_pipeline",
  "pddl": "_pddl",
  "plan": "_plan",
  "happenings": "_happenings",
  "prisma": "_prisma",
  "pp": "_puppet",
  "epp": "_puppet",
  "purs": "_purescript",
  "spec.jsx": "_react_1",
  "test.jsx": "_react_1",
  "cjsx": "_react",
  "spec.tsx": "_react_1",
  "test.tsx": "_react_1",
  "re": "_reasonml",
  "res": "_rescript",
  "resi": "_rescript_1",
  "rmd": "_R",
  "erb.html": "_html_erb",
  "html.erb": "_html_erb",
  "sass": "_sass",
  "springbeans": "_spring",
  "slim": "_slim",
  "smarty.tpl": "_smarty",
  "tpl": "_smarty",
  "sbt": "_sbt",
  "scala": "_scala",
  "sol": "_ethereum",
  "styl": "_stylus",
  "svelte": "_svelte",
  "soql": "_db_1",
  "tf": "_terraform",
  "tf.json": "_terraform",
  "tfvars": "_terraform",
  "tfvars.json": "_terraform",
  "dtx": "_tex_2",
  "ins": "_tex_3",
  "toml": "_config",
  "twig": "_twig",
  "spec.ts": "_typescript_1",
  "test.ts": "_typescript_1",
  "vala": "_vala",
  "vapi": "_vala",
  "component": "_html_3",
  "vue": "_vue",
  "wasm": "_wasm",
  "wat": "_wat",
  "pro": "_prolog",
  "zig": "_zig",
  "jar": "_zip",
  "zip": "_zip_1",
  "wgt": "_wgt",
  "ai": "_illustrator",
  "psd": "_photoshop",
  "pdf": "_pdf",
  "eot": "_font",
  "ttf": "_font",
  "woff": "_font",
  "woff2": "_font",
  "otf": "_font",
  "avif": "_image",
  "gif": "_image",
  "jpg": "_image",
  "jpeg": "_image",
  "png": "_image",
  "pxm": "_image",
  "svgx": "_image",
  "tiff": "_image",
  "webp": "_image",
  "sublime-project": "_sublime",
  "sublime-workspace": "_sublime",
  "mov": "_video",
  "ogv": "_video",
  "webm": "_video",
  "avi": "_video",
  "mpg": "_video",
  "mp4": "_video",
  "mp3": "_audio",
  "ogg": "_audio",
  "wav": "_audio",
  "flac": "_audio",
  "3ds": "_svg_1",
  "3dm": "_svg_1",
  "stl": "_svg_1",
  "obj": "_svg_1",
  "dae": "_svg_1",
  "babelrc.js": "_babel",
  "babelrc.cjs": "_babel",
  "bazelrc": "_bazel_1",
  "dockerignore": "_docker_1",
  "codeclimate.yml": "_code-climate",
  "eslintrc.js": "_eslint",
  "eslintrc.cjs": "_eslint",
  "eslintrc.yaml": "_eslint",
  "eslintrc.yml": "_eslint",
  "eslintignore": "_eslint_1",
  "firebaserc": "_firebase",
  "gitlab-ci.yml": "_gitlab",
  "stylelintrc": "_stylelint",
  "stylelintrc.json": "_stylelint",
  "stylelintrc.yaml": "_stylelint",
  "stylelintrc.yml": "_stylelint",
  "stylelintrc.js": "_stylelint",
  "stylelintignore": "_stylelint_1",
  "direnv": "_config",
  "static": "_config",
  "slugignore": "_config",
  "tmp": "_clock_1",
  "htaccess": "_config",
  "key": "_lock",
  "cert": "_lock",
  "cer": "_lock",
  "crt": "_lock",
  "pem": "_lock",
  "ds_store": "_ignored",
};

export const SETI_FILE_NAMES: Record<string, string> = {
  "settings.json": "_json",
  "launch.json": "_json",
  "tasks.json": "_json",
  "mcp.json": "_json",
  "keybindings.json": "_json",
  "extensions.json": "_json",
  "argv.json": "_json",
  "profiles.json": "_json",
  "devcontainer.json": "_json",
  ".devcontainer.json": "_json",
  "dockerfile": "_docker",
  "containerfile": "_docker",
  ".env": "_config",
  ".flaskenv": "_config",
  "user-dirs.dirs": "_config",
  ".vscodeignore": "_git",
  "commit_editmsg": "_git",
  "merge_msg": "_git",
  "jenkinsfile": "_jenkins",
  "gitconfig": "_config",
  "jakefile": "_javascript",
  "composer.lock": "_json",
  ".watchmanconfig": "_json",
  "babel.config.json": "_babel",
  "bun.lock": "_json",
  ".babelrc.json": "_json",
  ".ember-cli": "_json",
  "typedoc.json": "_json",
  "makefile": "_makefile",
  "gnumakefile": "_makefile",
  "ocamlmakefile": "_makefile",
  "skill.md": "_markdown",
  "sconstruct": "_python",
  "sconscript": "_python",
  "rakefile": "_ruby",
  "gemfile": "_ruby",
  "guardfile": "_ruby",
  "podfile": "_ruby",
  "capfile": "_ruby",
  "cheffile": "_ruby",
  "hobofile": "_ruby",
  "vagrantfile": "_ruby",
  "appraisals": "_ruby",
  "rantfile": "_ruby",
  "berksfile": "_ruby",
  "berksfile.lock": "_ruby",
  "thorfile": "_ruby",
  "puppetfile": "_ruby",
  "dangerfile": "_ruby",
  "brewfile": "_ruby",
  "fastfile": "_ruby",
  "appfile": "_ruby",
  "deliverfile": "_ruby",
  "matchfile": "_ruby",
  "scanfile": "_ruby",
  "snapfile": "_ruby",
  "gymfile": "_ruby",
  "apkbuild": "_shell",
  "pkgbuild": "_shell",
  ".envrc": "_shell",
  ".hushlogin": "_shell",
  "zshrc": "_shell",
  "zshenv": "_shell",
  "zlogin": "_shell",
  "zprofile": "_shell",
  "zlogout": "_shell",
  "bashrc_apple_terminal": "_shell",
  "zshrc_apple_terminal": "_shell",
  "tsconfig.json": "_tsconfig",
  "jsconfig.json": "_json",
  "mix": "_hex",
  "karma.conf.js": "_karma",
  "karma.conf.cjs": "_karma",
  "karma.conf.mjs": "_karma",
  "karma.conf.coffee": "_karma",
  "readme.md": "_info",
  "readme.txt": "_info",
  "readme": "_info",
  "changelog.md": "_clock",
  "changelog.txt": "_clock",
  "changelog": "_clock",
  "changes.md": "_clock",
  "changes.txt": "_clock",
  "changes": "_clock",
  "version.md": "_clock",
  "version.txt": "_clock",
  "version": "_clock",
  "mvnw": "_maven",
  "pom.xml": "_maven",
  "vite.config.js": "_vite",
  "vite.config.ts": "_vite",
  "vite.config.mjs": "_vite",
  "vite.config.mts": "_vite",
  "vite.config.cjs": "_vite",
  "vite.config.cts": "_vite",
  "swagger.json": "_json_1",
  "swagger.yml": "_json_1",
  "swagger.yaml": "_json_1",
  "mime.types": "_config",
  "babel.config.js": "_babel",
  "babel.config.cjs": "_babel",
  "build": "_bazel",
  "build.bazel": "_bazel",
  "workspace": "_bazel",
  "workspace.bazel": "_bazel",
  "bower.json": "_bower",
  "docker-healthcheck": "_docker_2",
  "eslint.config.js": "_eslint",
  "firebase.json": "_firebase",
  "geckodriver": "_firefox",
  "gruntfile.js": "_grunt",
  "gruntfile.babel.js": "_grunt",
  "gruntfile.coffee": "_grunt",
  "gulpfile": "_gulp",
  "gulpfile.js": "_gulp",
  "ionic.config.json": "_ionic",
  "ionic.project": "_ionic",
  "platformio.ini": "_platformio",
  "rollup.config.js": "_rollup",
  "sass-lint.yml": "_sass",
  "stylelint.config.js": "_stylelint",
  "stylelint.config.cjs": "_stylelint",
  "stylelint.config.mjs": "_stylelint",
  "yarn.clean": "_yarn",
  "yarn.lock": "_yarn",
  "webpack.config.js": "_webpack",
  "webpack.config.cjs": "_webpack",
  "webpack.config.mjs": "_webpack",
  "webpack.config.ts": "_webpack",
  "webpack.config.build.js": "_webpack",
  "webpack.config.build.cjs": "_webpack",
  "webpack.config.build.mjs": "_webpack",
  "webpack.config.build.ts": "_webpack",
  "webpack.common.js": "_webpack",
  "webpack.common.cjs": "_webpack",
  "webpack.common.mjs": "_webpack",
  "webpack.common.ts": "_webpack",
  "webpack.dev.js": "_webpack",
  "webpack.dev.cjs": "_webpack",
  "webpack.dev.mjs": "_webpack",
  "webpack.dev.ts": "_webpack",
  "webpack.prod.js": "_webpack",
  "webpack.prod.cjs": "_webpack",
  "webpack.prod.mjs": "_webpack",
  "webpack.prod.ts": "_webpack",
  "license": "_license",
  "licence": "_license",
  "license.txt": "_license",
  "licence.txt": "_license",
  "license.md": "_license",
  "licence.md": "_license",
  "copying": "_license",
  "copying.txt": "_license",
  "copying.md": "_license",
  "compiling": "_license_1",
  "compiling.txt": "_license_1",
  "compiling.md": "_license_1",
  "contributing": "_license_2",
  "contributing.txt": "_license_2",
  "contributing.md": "_license_2",
  "qmakefile": "_makefile_1",
  "omakefile": "_makefile_2",
  "cmakelists.txt": "_makefile_3",
  "procfile": "_heroku",
  "todo": "_todo",
  "todo.txt": "_todo",
  "todo.md": "_todo",
  "npm-debug.log": "_npm_ignored",
};

export interface SetiIcon { glyph: string; color: string; }

/** File icon-theme resolution: exact file name, then every dotted
 *  suffix ("a.test.ts" -> "test.ts" -> "ts"), then the generic file icon. */
export function setiIconFor(fileName: string): SetiIcon {
  const lower = String(fileName || '').toLowerCase();
  let id = SETI_FILE_NAMES[lower];
  if (!id) {
    const parts = lower.split('.');
    for (let index = 1; index < parts.length && !id; index += 1) {
      id = SETI_FILE_EXTENSIONS[parts.slice(index).join('.')];
    }
  }
  const definition = SETI_ICON_DEFS[id || SETI_DEFAULT_ID] || SETI_ICON_DEFS[SETI_DEFAULT_ID];
  return { glyph: definition[0], color: definition[1] };
}
