// The canonical TOOL_DEFS for the memory module. `public: false` entries are
// reachable through the in-process dispatcher (Pool C executors, synthetic
// tool registrations) but are not advertised via ListTools / tools.json, so
// they never reach an external LLM. `aiWrapped: true` routes dispatches
// through ai-wrapped-dispatch.mjs instead of the module's handleToolCall.
export const TOOL_DEFS = [
  {
    name: 'memory',
    title: 'Memory Cycle',
    annotations: { title: 'Memory Cycle', readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
    description: 'Persistent memory maintenance and explicit mutation. Use recall for retrieval; use memory only for status, lifecycle jobs, or intentional add/edit/delete/purge. Destructive jobs require exact confirm strings.',
    inputSchema: {
      type: 'object',
      properties: {
        action: { type: 'string', enum: ['core','manage','status','sleep','cycle1','cycle2','cycle3','flush','backfill','prune','rebuild','purge','retro_eval_active'], description: 'Operation to run: status/read jobs, core/manage mutation, lifecycle cycles, or destructive maintenance.' },
        op: { type: 'string', enum: ['add','edit','delete','list'], description: 'Mutation operation for action=core/manage.' },
        id: { type: 'number', description: 'Exact memory id for edit/delete; get it from recall or list output first.' },
        element: { type: 'string', description: 'Stable memory key/title for add/edit.' },
        summary: { type: 'string', description: 'Memory content to store or replace.' },
        category: { type: 'string', enum: ['rule','constraint','decision','fact','goal','preference','task','issue'], description: 'Memory category.' },
        status: { type: 'string', enum: ['pending','active','archived'], description: 'Entry lifecycle status for manage edit.' },
        maxDays: { type: 'number', description: 'Prune threshold in days for old unclassified entries.' },
        window: { type: 'string', description: 'Backfill/search window, e.g. 24h, 7d, 30d.' },
        limit: { type: 'number', description: 'Maximum rows/items for list, search, or backfill.' },
        concurrency: { type: 'number', description: 'Worker concurrency for supported maintenance jobs.' },
        sessionId: { type: 'string', description: 'Session id for scoped maintenance.' },
        session_id: { type: 'string', description: 'Alias for sessionId.' },
        window_size: { type: 'number', description: 'cycle1 rows per LLM window.' },
        rows_per_session: { type: 'number', description: 'cycle1 rows to fetch per session.' },
        confirm: { type: 'string', description: 'Exact confirmation phrase for destructive actions such as prune, rebuild, purge, or retro_eval_active.' },
        cycle3Mode: { type: 'string', enum: ['proposal','conservative'], description: 'cycle3 application mode; conservative applies only safe automatic changes.' },
        project_id: { type: 'string', description: 'Core memory project pool: common, owner/repo slug, or * for core list across pools.' },
      },
      required: ['action'],
    },
  },
  {
    name: 'recall',
    title: 'Recall',
    annotations: { title: 'Recall', readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    description: 'Retrieve stored memory (past decisions, prior work, session history). Use when the user references earlier work, when resuming a paused task, or before re-proposing something possibly already decided. query (string|array fan-out) and/or id; category/period/projectScope filters. Read-only and cheap — when in doubt, recall first.',
    inputSchema: {
      type: 'object',
      properties: {
        query: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' }, minItems: 1 }], description: 'Search text, or array for independent fan-out queries.' },
        id: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' }, minItems: 1 }], description: 'Only use exact #ids from a prior recall result. Do not invent ids, and do not combine id with query.' },
        period: { type: 'string', description: 'Time scope: last, 24h/7d/30d, all, YYYY-MM-DD, or YYYY-MM-DD~YYYY-MM-DD.' },
        limit: { type: 'number', description: 'Maximum entries to return.' },
        offset: { type: 'number', description: 'Skip N entries for paging.' },
        sort: { type: 'string', enum: ['importance', 'date'], description: 'importance (default relevance) or date (newest first).' },
        category: { anyOf: [{ type: 'string', enum: ['rule','constraint','decision','fact','goal','preference','task','issue'] }, { type: 'array', items: { type: 'string', enum: ['rule','constraint','decision','fact','goal','preference','task','issue'] }, minItems: 1 }], description: 'Optional category filter, string or array.' },
        includeArchived: { type: 'boolean', description: 'Include archived/historical entries; set false to focus on live/pending memory.' },
        sessionId: { type: 'string', description: 'Session id for scoped recall.' },
        session_id: { type: 'string', description: 'Alias for sessionId.' },
        includeMembers: { type: 'boolean', description: 'Include chunk member entries inline for session-scoped recall.' },
        projectScope: { type: 'string', description: 'Project pool selector: inferred from cwd, common, all, or a project slug.' },
        cwd: { type: 'string', description: 'Workspace path used to infer projectScope when projectScope is omitted.' },
      },
      additionalProperties: false,
    },
  },
  {
    name: 'search_memories',
    title: 'Search Memories',
    public: false,
    annotations: { title: 'Search Memories', readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    description: 'Search past context and memory. Returns root entries by default. Use when user references prior work, decisions, or preferences. Storage is automatic — only retrieval is manual.',
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search text. Triggers hybrid search (vector KNN + full-text BM25).' },
        period: { type: 'string', description: 'Time scope: "last" (before this session), "24h"/"3d"/"7d"/"30d" (relative), "all", "2026-04-05" (single day), "2026-04-01~2026-04-05" (range). Default: 30d when query set, latest entries otherwise.' },
        sort: { type: 'string', enum: ['date', 'importance'], description: 'date (newest first) or importance (score desc).' },
        category: { anyOf: [{ type: 'string', enum: ['rule','constraint','decision','fact','goal','preference','task','issue'] }, { type: 'array', items: { type: 'string', enum: ['rule','constraint','decision','fact','goal','preference','task','issue'] }, minItems: 1 }], description: 'Optional category filter for timeline/category recall.' },
        limit: { type: 'number', default: 30, description: 'Maximum entries to return.' },
        offset: { type: 'number', default: 0, description: 'Skip N entries for paging.' },
        includeMembers: { type: 'boolean', description: 'Include chunk member entries inline.' },
        includeRaw: { type: 'boolean', description: 'When true, fetch unclassified raw rows in the requested period window and merge into results. Caller-driven only — no auto-trigger.' },
        includeArchived: { type: 'boolean', description: 'Default true for historical recall. Set false to restrict to live/pending roots.' },
        sessionId: { type: 'string', description: 'Session id for scoped recall.' },
        session_id: { type: 'string', description: 'Alias for sessionId.' },
        projectScope: { type: 'string', description: 'Project pool selector. Omitted = infer from cwd, or `common` if unknown. Use `all` only when intentionally searching every project.' },
        cwd: { type: 'string', description: 'Optional workspace path, used only when `projectScope` is not set.' },
      },
      required: [],
    },
  },
]
