import { stdout } from 'node:process';

/** Help text printed by `--help`. */
export const HELP_LINES = [
  'mixdog — standalone mixdog CLI/TUI coding agent.',
  '',
  'Usage:',
  '  mixdog [options]           start the TUI in the current project',
  '  mixdog --provider <name> --model <name> [--effort <level>] [--fast] <role> <message...>',
  '  mixdog --help',
  '',
  'Options:',
  '  --provider <name>   provider route for this session',
  '  --model <name>      model route for this session',
  '  --effort <level>    reasoning effort for the selected model',
  '  --fast              enable Fast mode for the selected model',
  '  --workflow <name>   start with the given workflow active',
  '  --readonly          read-only tool surface',
  '  --remote            enable remote/channel mode for this session',
  '  --onboarding        re-run the first-run setup wizard',
  '',
  'Headless role commands require an explicit provider/model pair and run with',
  'ephemeral config/data; host behavioral config and personal state are not loaded.',
  'Roles: explore, worker, heavy-worker, reviewer, debugger, maintainer, web-researcher.',
  '',
  'Slash commands (inside mixdog):',
  '  /clear                        start a fresh chat (alias: /new)',
  '  /project [path]               switch working directory (project)',
  '  /compact                      compact older conversation context',
  '  /autoclear [on|off|duration]  reduce cache-miss cost after long idle gaps',
  '  /resume [id]                  resume a saved chat',
  '  /context                      show current context surface',
  '  /usage [refresh]              show total provider quota / balance',
  '  /model [name|refresh]         switch model for subsequent turns',
  '  /search                       set the web search provider/model',
  '  /workflow [name]              switch the active workflow',
  '  /OutputStyle [name]           switch Lead output style (alias: /style)',
  '  /theme [id]                   change the TUI color theme',
  '  /agents [refresh]             show available workflow agents',
  '  /effort [level]               set reasoning effort for the current model',
  '  /fast [on|off]                toggle Fast mode for the current model',
  '  /mcp                          manage MCP servers and tools',
  '  /skills                       choose a skill for the next request',
  '  /memory [status|core ...]     list and edit core memories',
  '  /plugins                      manage local plugin integrations',
  '  /hooks                        manage before-tool hook rules and events',
  '  /providers                    manage auth, API keys, OAuth, and local endpoints',
  '  /channels                     manage Discord, Telegram, and voice',
  '  /remote                       claim remote for this session',
  '  /setting                      open runtime settings (aliases: /settings, /config)',
  '  /profile                      set your title and response language',
  '  /update                       check version and update mixdog',
  '  /doctor                       diagnose installation health',
  '  /quit                         quit the TUI (aliases: /exit, /q)',
  '',
  'History: use ↑ / ↓ to recall previous inputs.',
];

/** Print the help text without importing the REPL/runtime stack. */
export function printHelp(write = (s) => stdout.write(s)) {
  write(`${HELP_LINES.join('\n')}\n`);
}
